package pe.interseguro.siv.common.util;

public interface ConstantesCRM {

	String COTIZACION_CONSENTIMIENTO_SI = "538560000";
	String COTIZACION_NO = "0";
	String COTIZACION_COMUNICACION_FUENTE_CORREO = "538560000";
	String COTIZACION_CONTRATANTE_IGUAL_ASEGURADO_SI = "1";
	String COTIZACION_CONTRATANTE_IGUAL_ASEGURADO_NO = "0";
	String COTIZACION_CONTRATANTE_FUMADOR_NO = "538560001";
	String COTIZACION_CONTRATANTE_TELEFONO_NUMERO_DEFECTO = "0";
	String COTIZACION_CONTRATANTE_PROFESION_ADMINISTRADOR = "538560003";
	String COTIZACION_CONTRATANTE_PROFESION_COTIZADOR_ADMINISTRADOR = "3";
	String COTIZACION_CONTRATANTE_ACTIVIDAD_ECONOMICA_ADMIN = "538560018";
	String COTIZACION_CONTRATANTE_DIRECCION_TIPO_PARTICULAR = "538560000";
	String COTIZACION_CONTRATANTE_DATOS_VIDA_INDIVIDUAL_AUDITORIA_OK = "538560000";
	String COTIZACION_DATOS_ADICIONALES_ENVIO_ESTADO_CUENTA = "538560002";

	String CONTACTO_CONSENTIMIENTO_SI = "538560000";
	String CONTACTO_CONSENTIMIENTO_NO = "538560001";
	String CONTACTO_CONSENTIMIENTO_FUENTE_ESCRITO = "538560001";
	String CONTACTO_CONSENTIMIENTO_VALIDACION_SI = "1";
	String CONTACTO_ADICIONALES_TELEFONO_PRINCIPAL = "538560001";
	String CONTACTO_ADICIONALES_TELEFONO_NUMERO_DEFECTO = "0";
	String CONTACTO_PERSONALES_PROFESION_ADMINISTRADOR = "538560003";
	String CONTACTO_DATOS_VIDA_INDIVIDUAL_ORIGEN_CLIENTE_POTENCIAL_REFERIDOS = "538560000";
	String CONTACTO_DATOS_VIDA_INDIVIDUAL_ACTIVIDAD_ECONOMICA_ADMIN = "538560018";
	String CONTACTO_DATOS_VIDA_INDIVIDUAL_AUDITORIA_OK = "538560000";
	String CONTACTO_DIRECCION_TIPO_PARTICULAR = "538560000";

	String DPS_RESPUESTA_SI = "1";
	String DPS_RESPUESTA_NO = "0";
	
	String BENEFICIARIO_FLAG_SI = "1";
	String BENEFICIARIO_FLAG_NO = "0";
}
