SELECT  * from dbo.PARAMETRO p2 ;
SELECT  * from DISTRITO p2 ;
SELECT  * from PERSONA p where TIPO_DOCUMENTO = '1' and NUMERO_DOCUMENTO = '76248069';
select * from HISTORIA_CLINICA hc ;
SELECT  * from PERSONA;
SELECT  * from DIAGNOSTICO d;
SELECT  de* from PROVINCIA p ;
SELECT  des* from DISTRITO p ;
select  DESCRIPCION * from DEPARTAMENTO d2 ;
SELECT * from PARAMETRO p2 WHERE NOMBRE_TABLA in ('GENERO','TIPO DOCUMENTO','ESTADO PERSONA','PERFIL PERSONA','TIPO PERSONA')  
select * from DISTRITO d ;
insert into dbo.PARAMETRO values (5,"C0003","Tipo de Documento Identidad", "1", "DNI", "1",1,"1","SYSTEM","2021-08-13 00:54:00");
SELECT (SELECT VALOR from PARAMETRO where NOMBRE_TABLA = 'GENERO' and CODIGO = 'C0001' )as SEXO from PARAMETRO p2 ;

EXEC SP_ODON_OBT_PARAMETRO 'C0003',null;
EXEC SP_ODON_OBT_PERSONA_X_DOC 1,74965244,null;
