package pe.interseguro.siv.common.persistence.db.mysql.domain;
// Generated May 20, 2019 8:07:22 PM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Adn generated by hbm2java
 */
@Entity
@Table(name = "adn", catalog = "siv_db")
public class Adn implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8667449156029488410L;
	private Long idAdn;
	private Persona persona;
	private String idAgente;
	private String idCircuitoFirma;
	private String idOportunidadCrm;
	private String ldpdp;
	private String ldpdpFecha;
	private String estado;
	private String usuarioCrea;
	private Date fechaCrea;
	private String usuarioModif;
	private Date fechaModif;

	
	public Adn() {
	}

	public Adn(Persona persona, String idAgente, String idCircuitoFirma, String usuarioCrea, Date fechaCrea) {
		this.persona = persona;
		this.idAgente = idAgente;
		this.idCircuitoFirma = idCircuitoFirma;
		this.usuarioCrea = usuarioCrea;
		this.fechaCrea = fechaCrea;
	}

	public Adn(Persona persona, String idAgente, String idCircuitoFirma, String idOportunidadCrm, String estado,
			String usuarioCrea, Date fechaCrea, String usuarioModif, Date fechaModif) {
		this.persona = persona;
		this.idAgente = idAgente;
		this.idCircuitoFirma = idCircuitoFirma;
		this.idOportunidadCrm = idOportunidadCrm;
		this.estado = estado;
		this.usuarioCrea = usuarioCrea;
		this.fechaCrea = fechaCrea;
		this.usuarioModif = usuarioModif;
		this.fechaModif = fechaModif;
	}
	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_adn", unique = true, nullable = false)
	public Long getIdAdn() {
		return this.idAdn;
	}

	public void setIdAdn(Long idAdn) {
		this.idAdn = idAdn;
	}

	//@ManyToOne(fetch = FetchType.LAZY)
	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "id_persona", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "id_agente", nullable = false, length = 50)
	public String getIdAgente() {
		return this.idAgente;
	}

	public void setIdAgente(String idAgente) {
		this.idAgente = idAgente;
	}

	@Column(name = "id_circuito_firma", nullable = false, length = 10)
	public String getIdCircuitoFirma() {
		return this.idCircuitoFirma;
	}

	public void setIdCircuitoFirma(String idCircuitoFirma) {
		this.idCircuitoFirma = idCircuitoFirma;
	}

	@Column(name = "id_oportunidad_crm", length = 50)
	public String getIdOportunidadCrm() {
		return this.idOportunidadCrm;
	}

	public void setIdOportunidadCrm(String idOportunidadCrm) {
		this.idOportunidadCrm = idOportunidadCrm;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "usuario_crea", nullable = false, length = 50)
	public String getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(String usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_crea", nullable = false, length = 19)
	public Date getFechaCrea() {
		return this.fechaCrea;
	}

	public void setFechaCrea(Date fechaCrea) {
		this.fechaCrea = fechaCrea;
	}

	@Column(name = "usuario_modif", length = 50)
	public String getUsuarioModif() {
		return this.usuarioModif;
	}

	public void setUsuarioModif(String usuarioModif) {
		this.usuarioModif = usuarioModif;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modif", length = 19)
	public Date getFechaModif() {
		return this.fechaModif;
	}

	public void setFechaModif(Date fechaModif) {
		this.fechaModif = fechaModif;
	}

	@Column(name = "ldpdp", length = 1)
	public String getLdpdp() {
		return ldpdp;
	}

	public void setLdpdp(String ldpdp) {
		this.ldpdp = ldpdp;
	}

	@Column(name = "lp_fecha", length = 20)
	public String getLdpdpFecha() {
		return ldpdpFecha;
	}

	public void setLdpdpFecha(String ldpdpFecha) {
		this.ldpdpFecha = ldpdpFecha;
	}

}
