package pe.interseguro.siv.common.persistence.db.mysql.domain;
// Generated May 20, 2019 8:07:22 PM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Autoguardado generated by hbm2java
 */
@Entity
@Table(name = "autoguardado", catalog = "siv_db", uniqueConstraints = {
	@UniqueConstraint(columnNames = "numero_documento"), 
	@UniqueConstraint(columnNames = "tipo_documento") 
})
public class Autoguardado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7792316700490894058L;
	private Long idAutoguardado;
	private String tipoDocumento;
	private String numeroDocumento;
	private byte[] datosJson;
	private String usuarioCrea;
	private Date fechaCrea;
	private String usuarioModif;
	private Date fechaModif;

	
	public Autoguardado() {
	}

	public Autoguardado(String tipoDocumento, String numeroDocumento, byte[] datosJson, String usuarioCrea,
			Date fechaCrea) {
		this.tipoDocumento = tipoDocumento;
		this.numeroDocumento = numeroDocumento;
		this.datosJson = datosJson;
		this.usuarioCrea = usuarioCrea;
		this.fechaCrea = fechaCrea;
	}

	public Autoguardado(String tipoDocumento, String numeroDocumento, byte[] datosJson, String usuarioCrea,
			Date fechaCrea, String usuarioModif, Date fechaModif) {
		this.tipoDocumento = tipoDocumento;
		this.numeroDocumento = numeroDocumento;
		this.datosJson = datosJson;
		this.usuarioCrea = usuarioCrea;
		this.fechaCrea = fechaCrea;
		this.usuarioModif = usuarioModif;
		this.fechaModif = fechaModif;
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_autoguardado", unique = true, nullable = false)
	public Long getIdAutoguardado() {
		return this.idAutoguardado;
	}

	public void setIdAutoguardado(Long idAutoguardado) {
		this.idAutoguardado = idAutoguardado;
	}

	@Column(name = "tipo_documento", unique = true, nullable = false, length = 1)
	public String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	@Column(name = "numero_documento", unique = true, nullable = false, length = 20)
	public String getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	@Column(name = "datos_json", nullable = false)
	public byte[] getDatosJson() {
		return this.datosJson;
	}

	public void setDatosJson(byte[] datosJson) {
		this.datosJson = datosJson;
	}

	@Column(name = "usuario_crea", nullable = false, length = 50)
	public String getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(String usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_crea", nullable = false, length = 19)
	public Date getFechaCrea() {
		return this.fechaCrea;
	}

	public void setFechaCrea(Date fechaCrea) {
		this.fechaCrea = fechaCrea;
	}

	@Column(name = "usuario_modif", length = 50)
	public String getUsuarioModif() {
		return this.usuarioModif;
	}

	public void setUsuarioModif(String usuarioModif) {
		this.usuarioModif = usuarioModif;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modif", length = 19)
	public Date getFechaModif() {
		return this.fechaModif;
	}

	public void setFechaModif(Date fechaModif) {
		this.fechaModif = fechaModif;
	}

}
