package pe.interseguro.siv.common.persistence.db.mysql.domain;
// Generated 10/09/2019 04:43:02 PM by Hibernate Tools 4.3.2-SNAPSHOT

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Solicitud generated by hbm2java
 */
@Entity
@Table(name = "codigo_verificacion", catalog = "siv_db")
public class CodigoVerificacionContratante implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -6665817468354448484L;
	
	private Long idCodigoVerificacion;
	private Long idSolicitud;
	private Long idPersona;
	private Long celular;
	private String codigo;
	private Integer enviado = 0;
	private Integer usado= 0;
	private Integer activo = 1;
	private Date fechaExpiracion = null;
	private Date fechaUsado = null;
	private String usuarioCrea = null;
	private Date fechaCrea = null;
	private String usuarioModif = null;
	private Date fechaModif = null;

	public CodigoVerificacionContratante() {
		this.activo = 1;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_codigo_verificacion", unique = true, nullable = false)
	public Long getIdCodigoVerificacion() {
	  return this.idCodigoVerificacion;
	}
	
	public void setIdCodigoVerificacion(Long idCodigoVerificacion) {
	  this.idCodigoVerificacion = idCodigoVerificacion;
	}
	
	@Column(name = "id_solicitud")
	public Long getIdSolicitud() {
	  return this.idSolicitud;
	}
	
	public void setIdSolicitud(Long idSolicitud) {
	  this.idSolicitud = idSolicitud;
	}
	
	@Column(name = "id_persona")
	public Long getIdPersona() {
	  return this.idPersona;
	}
	
	public void setIdPersona(Long idPersona) {
	  this.idPersona = idPersona;
	}
	
	@Column(name = "celular")
	public Long getCelular() {
	  return this.celular;
	}
	
	public void setCelular(Long celular) {
	  this.celular = celular;
	}
	
	@Column(name = "codigo")
	public String getCodigo() {
	  return this.codigo;
	}
	
	public void setCodigo(String codigo) {
	  this.codigo = codigo;
	}
	
	@Column(name = "enviado")
	public Integer getEnviado() {
	  return this.enviado;
	}
	
	public void setEnviado(Integer enviado) {
	  this.enviado = enviado;
	}
	
	@Column(name = "usado")
	public Integer getUsado() {
	  return this.usado;
	}
	
	public void setUsado(Integer usado) {
	  this.usado = usado;
	}
	
	@Column(name = "activo")
	public Integer getActivo() {
	  return this.activo;
	}
	
	public void setActivo(Integer activo) {
	  this.activo = activo;
	}
	
	@Column(name = "fecha_expiracion")
	public Date getFechaExpiracion() {
	  return this.fechaExpiracion;
	}
	
	public void setFechaExpiracion(Date fechaExpiracion) {
	  this.fechaExpiracion = fechaExpiracion;
	}
	
	@Column(name = "fecha_usado")
	public Date getFechaUsado() {
	  return this.fechaUsado;
	}
	
	public void setFechaUsado(Date fechaUsado) {
	  this.fechaUsado = fechaUsado;
	}
	
	@Column(name = "usuario_crea")
	public String getUsuarioCrea() {
	  return this.usuarioCrea;
	}
	
	public void setUsuarioCrea(String usuarioCrea) {
	  this.usuarioCrea = usuarioCrea;
	}
	
	@Column(name = "fecha_crea")
	public Date getFechaCrea() {
	  return this.fechaCrea;
	}
	
	public void setFechaCrea(Date fechaCrea) {
	  this.fechaCrea = fechaCrea;
	}
	
	@Column(name = "usuario_modif")
	public String getUsuarioModif() {
	  return this.usuarioModif;
	}
	
	public void setUsuarioModif(String usuarioModif) {
	  this.usuarioModif = usuarioModif;
	}
	
	@Column(name = "fecha_modif")
	public Date getFechaModif() {
	  return this.fechaModif;
	}
	
	public void setFechaModif(Date fechaModif) {
	  this.fechaModif = fechaModif;
	}

}
