package pe.interseguro.siv.common.persistence.db.mysql.domain;
// Generated May 20, 2019 8:07:22 PM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Familiar generated by hbm2java
 */
@Entity
@Table(name = "familiar", catalog = "siv_db")
public class Familiar implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2939267613890918197L;
	private Long idFamiliar;
	private Persona persona;
	private String tipoRelacion;
	private String nombres;
	private Integer edad;
	private String centroLaboral;
	private String usuarioCrea;
	private Date fechaCrea;
	private String usuarioModif;
	private String fechaModif;

	
	public Familiar() {
	}

	public Familiar(Persona persona, String usuarioCrea, Date fechaCrea) {
		this.persona = persona;
		this.usuarioCrea = usuarioCrea;
		this.fechaCrea = fechaCrea;
	}

	public Familiar(Persona persona, String tipoRelacion, String nombres, Integer edad, String usuarioCrea,
			Date fechaCrea, String usuarioModif, String fechaModif) {
		this.persona = persona;
		this.tipoRelacion = tipoRelacion;
		this.nombres = nombres;
		this.edad = edad;
		this.usuarioCrea = usuarioCrea;
		this.fechaCrea = fechaCrea;
		this.usuarioModif = usuarioModif;
		this.fechaModif = fechaModif;
	}
	
	public Familiar(Persona persona, String tipoRelacion, String nombres, Integer edad, String centroLaboral, 
			String usuarioCrea, Date fechaCrea, String usuarioModif, String fechaModif) {
		this.persona = persona;
		this.tipoRelacion = tipoRelacion;
		this.nombres = nombres;
		this.edad = edad;
		this.centroLaboral = centroLaboral;
		this.usuarioCrea = usuarioCrea;
		this.fechaCrea = fechaCrea;
		this.usuarioModif = usuarioModif;
		this.fechaModif = fechaModif;
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_familiar", unique = true, nullable = false)
	public Long getIdFamiliar() {
		return this.idFamiliar;
	}

	public void setIdFamiliar(Long idFamiliar) {
		this.idFamiliar = idFamiliar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "tipo_relacion", length = 1)
	public String getTipoRelacion() {
		return this.tipoRelacion;
	}

	public void setTipoRelacion(String tipoRelacion) {
		this.tipoRelacion = tipoRelacion;
	}

	@Column(name = "nombres", length = 200)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "edad")
	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	@Column(name = "usuario_crea", nullable = false, length = 50)
	public String getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(String usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_crea", nullable = false, length = 19)
	public Date getFechaCrea() {
		return this.fechaCrea;
	}

	public void setFechaCrea(Date fechaCrea) {
		this.fechaCrea = fechaCrea;
	}

	@Column(name = "usuario_modif", length = 50)
	public String getUsuarioModif() {
		return this.usuarioModif;
	}

	public void setUsuarioModif(String usuarioModif) {
		this.usuarioModif = usuarioModif;
	}

	@Column(name = "fecha_modif", length = 45)
	public String getFechaModif() {
		return this.fechaModif;
	}

	public void setFechaModif(String fechaModif) {
		this.fechaModif = fechaModif;
	}

	@Column(name = "centro_laboral")
	public String getCentroLaboral() {
		return centroLaboral;
	}

	public void setCentroLaboral(String centroLaboral) {
		this.centroLaboral = centroLaboral;
	}

}
