package pe.interseguro.siv.common.persistence.db.mysql.domain;
// Generated May 20, 2019 8:07:22 PM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Multitabla generated by hbm2java
 */
@Entity
@Table(name = "multitabla", catalog = "siv_db")
public class Multitabla implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 921592246369905084L;
	private Long idMultitabla;
	private String codigoTabla;
	private String nombreTabla;
	private String codigo;
	private Integer orden;
	private String valor;
	private String valorAux;
	private String valorCrm;
	private String valorFlex;
	private String estado;
	private String estadoTabla;
	private String usuarioCrea;
	private Date fechaCrea;
	private String usuarioModif;
	private Date fechaModif;

	
	public Multitabla() {
	}

	public Multitabla(String codigoTabla, String nombreTabla, String estadoTabla, String usuarioCrea, Date fechaCrea) {
		this.codigoTabla = codigoTabla;
		this.nombreTabla = nombreTabla;
		this.estadoTabla = estadoTabla;
		this.usuarioCrea = usuarioCrea;
		this.fechaCrea = fechaCrea;
	}

	public Multitabla(String codigoTabla, String nombreTabla, String codigo, Integer orden, String valor,
			String valorAux, String valorCrm, String valorFlex, String estado, String estadoTabla, String usuarioCrea, Date fechaCrea,
			String usuarioModif, Date fechaModif) {
		this.codigoTabla = codigoTabla;
		this.nombreTabla = nombreTabla;
		this.codigo = codigo;
		this.orden = orden;
		this.valor = valor;
		this.valorAux = valorAux;
		this.valorCrm = valorCrm;
		this.valorFlex = valorFlex;
		this.estado = estado;
		this.estadoTabla = estadoTabla;
		this.usuarioCrea = usuarioCrea;
		this.fechaCrea = fechaCrea;
		this.usuarioModif = usuarioModif;
		this.fechaModif = fechaModif;
	}
	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_multitabla", unique = true, nullable = false)
	public Long getIdMultitabla() {
		return this.idMultitabla;
	}

	public void setIdMultitabla(Long idMultitabla) {
		this.idMultitabla = idMultitabla;
	}

	@Column(name = "codigo_tabla", nullable = false, length = 3)
	public String getCodigoTabla() {
		return this.codigoTabla;
	}

	public void setCodigoTabla(String codigoTabla) {
		this.codigoTabla = codigoTabla;
	}

	@Column(name = "nombre_tabla", nullable = false, length = 100)
	public String getNombreTabla() {
		return this.nombreTabla;
	}

	public void setNombreTabla(String nombreTabla) {
		this.nombreTabla = nombreTabla;
	}

	@Column(name = "codigo", length = 100)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "valor", length = 200)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Column(name = "valor_aux", length = 200)
	public String getValorAux() {
		return this.valorAux;
	}

	public void setValorAux(String valorAux) {
		this.valorAux = valorAux;
	}

	@Column(name = "valor_crm", length = 200)
	public String getValorCrm() {
		return this.valorCrm;
	}

	public void setValorCrm(String valorCrm) {
		this.valorCrm = valorCrm;
	}

	@Column(name = "estado", length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "estado_tabla", nullable = false, length = 1)
	public String getEstadoTabla() {
		return this.estadoTabla;
	}

	public void setEstadoTabla(String estadoTabla) {
		this.estadoTabla = estadoTabla;
	}

	@Column(name = "usuario_crea", nullable = false, length = 50)
	public String getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(String usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_crea", nullable = false, length = 19)
	public Date getFechaCrea() {
		return this.fechaCrea;
	}

	public void setFechaCrea(Date fechaCrea) {
		this.fechaCrea = fechaCrea;
	}

	@Column(name = "usuario_modif", length = 50)
	public String getUsuarioModif() {
		return this.usuarioModif;
	}

	public void setUsuarioModif(String usuarioModif) {
		this.usuarioModif = usuarioModif;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modif", length = 19)
	public Date getFechaModif() {
		return this.fechaModif;
	}

	public void setFechaModif(Date fechaModif) {
		this.fechaModif = fechaModif;
	}

	@Column(name = "valor_flex", length = 10)
	public String getValorFlex() {
		return valorFlex;
	}

	public void setValorFlex(String valorFlex) {
		this.valorFlex = valorFlex;
	}

}
