package pe.interseguro.siv.common.persistence.db.mysql.domain;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PersonaConsentimiento generated by hbm2java
 */
@Entity
@Table(name = "persona_consentimiento", catalog = "siv_db")
public class PersonaConsentimiento implements Serializable {

    private static final long serialVersionUID = 1L;
    
    private Integer idPersonaConsentimiento;
    private String tipoDocumento;
    private String numeroDocumento;
    private Integer estadoLpdp;
    private String usuarioCrea;
    private Date fechaCrea;
    private String usuarioModif;
    private Date fechaModif;
    private Integer tokenConsentimientoUsado;

    public PersonaConsentimiento() {
    }

    public PersonaConsentimiento(String tipoDocumento, String numeroDocumento, Integer estadoLpdp, String usuarioCrea, Date fechaCrea) {
        this.tipoDocumento = tipoDocumento;
        this.numeroDocumento = numeroDocumento;
        this.estadoLpdp = estadoLpdp;
        this.usuarioCrea = usuarioCrea;
        this.fechaCrea = fechaCrea;
    }

    public PersonaConsentimiento(String tipoDocumento, String numeroDocumento, Integer estadoLpdp, String usuarioCrea, Date fechaCrea, String usuarioModif, Date fechaModif) {
        this.tipoDocumento = tipoDocumento;
        this.numeroDocumento = numeroDocumento;
        this.estadoLpdp = estadoLpdp;
        this.usuarioCrea = usuarioCrea;
        this.fechaCrea = fechaCrea;
        this.usuarioModif = usuarioModif;
        this.fechaModif = fechaModif;
    }

    public PersonaConsentimiento(String tipoDocumento, String numeroDocumento, Integer estadoLpdp, String usuarioCrea, Date fechaCrea, String usuarioModif, Date fechaModif, Integer tokenConsentimientoUsado) {
        this.tipoDocumento = tipoDocumento;
        this.numeroDocumento = numeroDocumento;
        this.estadoLpdp = estadoLpdp;
        this.usuarioCrea = usuarioCrea;
        this.fechaCrea = fechaCrea;
        this.usuarioModif = usuarioModif;
        this.fechaModif = fechaModif;
        this.tokenConsentimientoUsado = tokenConsentimientoUsado;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_persona_consentimiento", unique = true, nullable = false)
    public Integer getIdPersonaConsentimiento() {
        return this.idPersonaConsentimiento;
    }

    public void setIdPersonaConsentimiento(Integer idPersonaConsentimiento) {
        this.idPersonaConsentimiento = idPersonaConsentimiento;
    }

    @Column(name = "tipo_documento", nullable = false, length = 2)
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }

    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }

    @Column(name = "numero_documento", nullable = false, length = 20)
    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }

    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }

    @Column(name = "estado_lpdp", nullable = false)
    public Integer getEstadoLpdp() {
        return this.estadoLpdp;
    }

    public void setEstadoLpdp(Integer estadoLpdp) {
        this.estadoLpdp = estadoLpdp;
    }

    @Column(name = "usuario_crea", nullable = false, length = 50)
    public String getUsuarioCrea() {
        return this.usuarioCrea;
    }

    public void setUsuarioCrea(String usuarioCrea) {
        this.usuarioCrea = usuarioCrea;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_crea", nullable = false, length = 19)
    public Date getFechaCrea() {
        return this.fechaCrea;
    }

    public void setFechaCrea(Date fechaCrea) {
        this.fechaCrea = fechaCrea;
    }

    @Column(name = "usuario_modif", length = 50)
    public String getUsuarioModif() {
        return this.usuarioModif;
    }

    public void setUsuarioModif(String usuarioModif) {
        this.usuarioModif = usuarioModif;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_modif", length = 19)
    public Date getFechaModif() {
        return this.fechaModif;
    }

    public void setFechaModif(Date fechaModif) {
        this.fechaModif = fechaModif;
    }

    @Column(name = "token_consentimiento_usado")
    public Integer getTokenConsentimientoUsado() {
        return this.tokenConsentimientoUsado;
    }

    public void setTokenConsentimientoUsado(Integer tokenConsentimientoUsado) {
        this.tokenConsentimientoUsado = tokenConsentimientoUsado;
    }
} 