package pe.interseguro.siv.common.persistence.db.mysql.domain;
// Generated 03/09/2019 02:25:16 PM by Hibernate Tools 4.3.2-SNAPSHOT


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;


/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="persona"
    ,catalog="siv_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="numero_documento") 
)
public class Persona  implements Serializable {

	 private static final long serialVersionUID = 3328308824028000593L;
     private Long idPersona;
     private String tipoDocumento;
     private String numeroDocumento;
     private Date fechaNacimiento;
     private Integer edadActuarial;
     private String nombres;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String genero;
     private Integer celular;
     private String correo;
     private String profesion;
     private String actividadEconomica;
     private String lugarTrabajo;
     private String fumador;
     private String usuarioCrea;
     private Date fechaCrea;
     private String usuarioModif;
     private Date fechaModif;
     private String razonSocial;
     private String estadoCivil;
     private String nacionalidad;
     private String direccionTipo;
     private String direccionTipoDes;
     private String direccionNroMz;
     private String direccionInterior;
     private String direccionUrbanizacion;
     private String departamento;
     private String provincia;
     private String distrito;
     private String esPep;
     private String esSujetoObligado;
     private String centroTrabajo;
     private String ingresoMoneda;
     private Integer ingresoValor;
     private String profesionDetalle;
     private String tipoCasa;
     private String tieneVehiculo;
     private String tieneAfp;
     private String tieneSeguroVida;
     private String actualizadoLead;
     private String documentoAdn;
    private String idPersonaCS;

    private Set<Adn> adns = new HashSet<Adn>(0);
     private Set<Referido> referidos = new HashSet<Referido>(0);
     private Set<Solicitud> solicitudsForIdContratante = new HashSet<Solicitud>(0);
     private Set<Solicitud> solicitudsForIdAsegurado = new HashSet<Solicitud>(0);
     private Set<Familiar> familiars = new HashSet<Familiar>(0);
     private Set<PlanFuturo> planFuturos = new HashSet<PlanFuturo>(0);

    public Persona() {
    }

	
    public Persona(String tipoDocumento, String numeroDocumento, Date fechaNacimiento, String nombres, String apellidoPaterno, String apellidoMaterno, String genero, String usuarioCrea, Date fechaCrea) {
        this.tipoDocumento = tipoDocumento;
        this.numeroDocumento = numeroDocumento;
        this.fechaNacimiento = fechaNacimiento;
        this.nombres = nombres;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.genero = genero;
        this.usuarioCrea = usuarioCrea;
        this.fechaCrea = fechaCrea;
    }
    public Persona(String tipoDocumento, String numeroDocumento, Date fechaNacimiento, Integer edadActuarial, String nombres, String apellidoPaterno, String apellidoMaterno, String genero, Integer celular, String correo, String profesion, String lugarTrabajo, String actividadEconomica, String fumador, String usuarioCrea, Date fechaCrea, String usuarioModif, Date fechaModif, String razonSocial, String estadoCivil, String nacionalidad, String direccionTipo, String direccionTipoDes, String direccionNroMz, String direccionInterior, String direccionUrbanizacion, String departamento, String provincia, String distrito, String esPep, String esSujetoObligado, String centroTrabajo, String ingresoMoneda, Integer ingresoValor, String profesionDetalle, String documentoAdn, Set<Adn> adns, Set<Referido> referidos, Set<Solicitud> solicitudsForIdContratante, Set<Solicitud> solicitudsForIdAsegurado, Set<Familiar> familiars, Set<PlanFuturo> planFuturos) {
       this.tipoDocumento = tipoDocumento;
       this.numeroDocumento = numeroDocumento;
       this.fechaNacimiento = fechaNacimiento;
       this.edadActuarial = edadActuarial;
       this.nombres = nombres;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.genero = genero;
       this.celular = celular;
       this.correo = correo;
       this.profesion = profesion;
       this.actividadEconomica = actividadEconomica;
       this.lugarTrabajo = lugarTrabajo;
       this.fumador = fumador;
       this.usuarioCrea = usuarioCrea;
       this.fechaCrea = fechaCrea;
       this.usuarioModif = usuarioModif;
       this.fechaModif = fechaModif;
       this.razonSocial = razonSocial;
       this.estadoCivil = estadoCivil;
       this.nacionalidad = nacionalidad;
       this.direccionTipo = direccionTipo;
       this.direccionTipoDes = direccionTipoDes;
       this.direccionNroMz = direccionNroMz;
       this.direccionInterior = direccionInterior;
       this.direccionUrbanizacion = direccionUrbanizacion;
       this.departamento = departamento;
       this.provincia = provincia;
       this.distrito = distrito;
       this.esPep = esPep;
       this.esSujetoObligado = esSujetoObligado;
       this.centroTrabajo = centroTrabajo;
       this.ingresoMoneda = ingresoMoneda;
       this.ingresoValor = ingresoValor;
       this.profesionDetalle = profesionDetalle;
       this.adns = adns;
       this.referidos = referidos;
       this.solicitudsForIdContratante = solicitudsForIdContratante;
       this.solicitudsForIdAsegurado = solicitudsForIdAsegurado;
       this.familiars = familiars;
       this.planFuturos = planFuturos;
       this.documentoAdn= documentoAdn;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_persona", unique=true, nullable=false)
    public Long getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Long idPersona) {
        this.idPersona = idPersona;
    }

    
    @Column(name="tipo_documento", nullable=false, length=1)
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }

    
    @Column(name="numero_documento", unique=true, nullable=false, length=20)
    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_nacimiento", nullable=false, length=19)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    
    @Column(name="edad_actuarial")
    public Integer getEdadActuarial() {
        return this.edadActuarial;
    }
    
    public void setEdadActuarial(Integer edadActuarial) {
        this.edadActuarial = edadActuarial;
    }

    
    @Column(name="nombres", nullable=false, length=100)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellido_paterno", nullable=false, length=50)
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }

    
    @Column(name="apellido_materno", nullable=false, length=50)
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }

    
    @Column(name="genero", nullable=false, length=1)
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }

    
    @Column(name="celular")
    public Integer getCelular() {
        return this.celular;
    }
    
    public void setCelular(Integer celular) {
        this.celular = celular;
    }

    
    @Column(name="correo", length=200)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="profesion", length=3)
    public String getProfesion() {
        return this.profesion;
    }
    
    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }

    
    @Column(name="actividad_economica", length=3)
    public String getActividadEconomica() {
        return this.actividadEconomica;
    }
    
    public void setActividadEconomica(String actividadEconomica) {
        this.actividadEconomica = actividadEconomica;
    }
    
    @Column(name="lugarTrabajo", length=3)
    public String getLugarTrabajo() {
        return this.lugarTrabajo;
    }

    public void setLugarTrabajo(String lugarTrabajo) {
        this.lugarTrabajo = lugarTrabajo;
    }
    
    @Column(name="fumador", length=1)
    public String getFumador() {
        return this.fumador;
    }
    
    public void setFumador(String fumador) {
        this.fumador = fumador;
    }

    
    @Column(name="usuario_crea", nullable=false, length=50)
    public String getUsuarioCrea() {
        return this.usuarioCrea;
    }
    
    public void setUsuarioCrea(String usuarioCrea) {
        this.usuarioCrea = usuarioCrea;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_crea", nullable=false, length=19)
    public Date getFechaCrea() {
        return this.fechaCrea;
    }
    
    public void setFechaCrea(Date fechaCrea) {
        this.fechaCrea = fechaCrea;
    }

    
    @Column(name="usuario_modif", length=50)
    public String getUsuarioModif() {
        return this.usuarioModif;
    }
    
    public void setUsuarioModif(String usuarioModif) {
        this.usuarioModif = usuarioModif;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modif", length=19)
    public Date getFechaModif() {
        return this.fechaModif;
    }
    
    public void setFechaModif(Date fechaModif) {
        this.fechaModif = fechaModif;
    }

    
    @Column(name="razon_social", length=100)
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    
    @Column(name="estado_civil", length=1)
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }

    
    @Column(name="nacionalidad", length=3)
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }

    
    @Column(name="direccion_tipo", length=1)
    public String getDireccionTipo() {
        return this.direccionTipo;
    }
    
    public void setDireccionTipo(String direccionTipo) {
        this.direccionTipo = direccionTipo;
    }

    
    @Column(name="direccion_tipo_des", length=100)
    public String getDireccionTipoDes() {
        return this.direccionTipoDes;
    }
    
    public void setDireccionTipoDes(String direccionTipoDes) {
        this.direccionTipoDes = direccionTipoDes;
    }

    
    @Column(name="direccion_nro_mz", length=20)
    public String getDireccionNroMz() {
        return this.direccionNroMz;
    }
    
    public void setDireccionNroMz(String direccionNroMz) {
        this.direccionNroMz = direccionNroMz;
    }

    
    @Column(name="direccion_interior", length=20)
    public String getDireccionInterior() {
        return this.direccionInterior;
    }
    
    public void setDireccionInterior(String direccionInterior) {
        this.direccionInterior = direccionInterior;
    }

    
    @Column(name="direccion_urbanizacion", length=45)
    public String getDireccionUrbanizacion() {
        return this.direccionUrbanizacion;
    }
    
    public void setDireccionUrbanizacion(String direccionUrbanizacion) {
        this.direccionUrbanizacion = direccionUrbanizacion;
    }

    
    @Column(name="departamento", length=3)
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }

    
    @Column(name="provincia", length=3)
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }

    
    @Column(name="distrito", length=4)
    public String getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(String distrito) {
        this.distrito = distrito;
    }

    
    @Column(name="es_pep", length=1)
    public String getEsPep() {
        return this.esPep;
    }
    
    public void setEsPep(String esPep) {
        this.esPep = esPep;
    }

    
    @Column(name="es_sujeto_obligado", length=1)
    public String getEsSujetoObligado() {
        return this.esSujetoObligado;
    }
    
    public void setEsSujetoObligado(String esSujetoObligado) {
        this.esSujetoObligado = esSujetoObligado;
    }

    
    @Column(name="centro_trabajo", length=100)
    public String getCentroTrabajo() {
        return this.centroTrabajo;
    }
    
    public void setCentroTrabajo(String centroTrabajo) {
        this.centroTrabajo = centroTrabajo;
    }

    
    @Column(name="ingreso_moneda", length=1)
    public String getIngresoMoneda() {
        return this.ingresoMoneda;
    }
    
    public void setIngresoMoneda(String ingresoMoneda) {
        this.ingresoMoneda = ingresoMoneda;
    }

    
    @Column(name="ingreso_valor")
    public Integer getIngresoValor() {
        return this.ingresoValor;
    }
    
    public void setIngresoValor(Integer ingresoValor) {
        this.ingresoValor = ingresoValor;
    }

    
    @Column(name="profesion_detalle", length=100)
    public String getProfesionDetalle() {
        return this.profesionDetalle;
    }
    
    public void setProfesionDetalle(String profesionDetalle) {
        this.profesionDetalle = profesionDetalle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set<Adn> getAdns() {
        return this.adns;
    }
    
    public void setAdns(Set<Adn> adns) {
        this.adns = adns;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set<Referido> getReferidos() {
        return this.referidos;
    }
    
    public void setReferidos(Set<Referido> referidos) {
        this.referidos = referidos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personaByIdContratante")
    public Set<Solicitud> getSolicitudsForIdContratante() {
        return this.solicitudsForIdContratante;
    }
    
    public void setSolicitudsForIdContratante(Set<Solicitud> solicitudsForIdContratante) {
        this.solicitudsForIdContratante = solicitudsForIdContratante;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personaByIdAsegurado")
    public Set<Solicitud> getSolicitudsForIdAsegurado() {
        return this.solicitudsForIdAsegurado;
    }
    
    public void setSolicitudsForIdAsegurado(Set<Solicitud> solicitudsForIdAsegurado) {
        this.solicitudsForIdAsegurado = solicitudsForIdAsegurado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set<Familiar> getFamiliars() {
        return this.familiars;
    }
    
    public void setFamiliars(Set<Familiar> familiars) {
        this.familiars = familiars;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="persona")
    public Set<PlanFuturo> getPlanFuturos() {
        return this.planFuturos;
    }
    
    public void setPlanFuturos(Set<PlanFuturo> planFuturos) {
        this.planFuturos = planFuturos;
    }

    @Column(name="tipo_casa", length=50)
	public String getTipoCasa() {
		return tipoCasa;
	}

	public void setTipoCasa(String tipoCasa) {
		this.tipoCasa = tipoCasa;
	}

	 @Column(name="tiene_vehiculo", length=1)
	public String getTieneVehiculo() {
		return tieneVehiculo;
	}

	public void setTieneVehiculo(String tieneVehiculo) {
		this.tieneVehiculo = tieneVehiculo;
	}

	@Column(name="tiene_afp", length=1)
	public String getTieneAfp() {
		return tieneAfp;
	}

	public void setTieneAfp(String tieneAfp) {
		this.tieneAfp = tieneAfp;
	}

	@Column(name="tiene_seguro", length=1)
	public String getTieneSeguroVida() {
		return tieneSeguroVida;
	}

	public void setTieneSeguroVida(String tieneSeguroVida) {
		this.tieneSeguroVida = tieneSeguroVida;
	}

    @Column(name="actualizado_lead", length=1)
    public String getActualizadoLead() {
        return actualizadoLead;
    }

    public void setActualizadoLead(String actualizadoLead) {
        this.actualizadoLead = actualizadoLead;
    }
    
	@Column(name = "documento_adn", length = 500)
	public String getDocumentoAdn() {
		return documentoAdn;
	}

	public void setDocumentoAdn(String documentoAdn) {
		this.documentoAdn = documentoAdn;
	}

    @Column(name = "idPersonaCS", length = 500)
    public String getIdPersonaCS() {
        return idPersonaCS;
    }

    public void setIdPersonaCS(String idPersonaCS) {
        this.idPersonaCS = idPersonaCS;
    }


}
