package pe.interseguro.siv.common.persistence.db.mysql.domain;
// Generated May 23, 2019 12:42:23 PM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PlanFuturo generated by hbm2java
 */
@Entity
@Table(name = "plan_futuro", catalog = "siv_db")
public class PlanFuturo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2182744768612083539L;
	private Long idPlanFuturo;
	private Persona persona;
	private Integer planEducacion;
	private Integer planProyecto;
	private Integer planJubilacion;
	private Float ingresoTitular;
	private Float porcentajeInversion;
	private Float totalInversion;
	private Integer aniosProteger;
	private Float respaldoAhorros;
	private Integer respaldoAhorrosCheck;
	private Float respaldoPropiedades;
	private Integer respaldoPropiedadesCheck;
	private Float respaldoVehiculos;
	private Integer respaldoVehiculosCheck;
	private Float respaldoSeguroVida;
	private Integer respaldoSeguroVidaCheck;
	private Float respaldoSeguroVidaLey;
	private Integer respaldoSeguroVidaLeyCheck;
	private Float capitalProteccion;
	private Float capitalRespaldo;
	private Float capitalAfp;
	private Integer capitalAfpCheck;
	private Float capitalTotalProteger;
	private Float capitalAdicional;
	private Float capitalTotalProtegerNuevo;
	private String informacionAdicional;
	private String usuarioCrea;
	private Date fechaCrea;
	private String usuarioModif;
	private String fechaModif;

	public PlanFuturo() {
	}

	public PlanFuturo(Persona persona, String usuarioCrea, Date fechaCrea) {
		this.persona = persona;
		this.usuarioCrea = usuarioCrea;
		this.fechaCrea = fechaCrea;
	}

	public PlanFuturo(Persona persona, Integer planEducacion, Integer planProyecto, Integer planJubilacion, Float ingresoTitular,
			Float porcentajeInversion, Float totalInversion, Integer aniosProteger, Float respaldoAhorros,
			Integer respaldoAhorrosCheck, Float respaldoPropiedades, Integer respaldoPropiedadesCheck,
			Float respaldoVehiculos, Integer respaldoVehiculosCheck, Float respaldoSeguroVida,
			Integer respaldoSeguroVidaCheck, Float respaldoSeguroVidaLey, Integer respaldoSeguroVidaLeyCheck,
			Float capitalProteccion, Float capitalRespaldo, Float capitalAfp, Integer capitalAfpCheck,
			Float capitalTotalProteger, Float capitalAdicional, Float capitalTotalProtegerNuevo, String usuarioCrea,
			Date fechaCrea, String usuarioModif, String fechaModif) {
		this.persona = persona;
		this.planEducacion = planEducacion;
		this.planProyecto = planProyecto;
		this.planJubilacion = planJubilacion;
		this.ingresoTitular = ingresoTitular;
		this.porcentajeInversion = porcentajeInversion;
		this.totalInversion = totalInversion;
		this.aniosProteger = aniosProteger;
		this.respaldoAhorros = respaldoAhorros;
		this.respaldoAhorrosCheck = respaldoAhorrosCheck;
		this.respaldoPropiedades = respaldoPropiedades;
		this.respaldoPropiedadesCheck = respaldoPropiedadesCheck;
		this.respaldoVehiculos = respaldoVehiculos;
		this.respaldoVehiculosCheck = respaldoVehiculosCheck;
		this.respaldoSeguroVida = respaldoSeguroVida;
		this.respaldoSeguroVidaCheck = respaldoSeguroVidaCheck;
		this.respaldoSeguroVidaLey = respaldoSeguroVidaLey;
		this.respaldoSeguroVidaLeyCheck = respaldoSeguroVidaLeyCheck;
		this.capitalProteccion = capitalProteccion;
		this.capitalRespaldo = capitalRespaldo;
		this.capitalAfp = capitalAfp;
		this.capitalAfpCheck = capitalAfpCheck;
		this.capitalTotalProteger = capitalTotalProteger;
		this.capitalAdicional = capitalAdicional;
		this.capitalTotalProtegerNuevo = capitalTotalProtegerNuevo;
		this.usuarioCrea = usuarioCrea;
		this.fechaCrea = fechaCrea;
		this.usuarioModif = usuarioModif;
		this.fechaModif = fechaModif;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_plan_futuro", unique = true, nullable = false)
	public Long getIdPlanFuturo() {
		return this.idPlanFuturo;
	}

	public void setIdPlanFuturo(Long idPlanFuturo) {
		this.idPlanFuturo = idPlanFuturo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_persona", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "plan_educacion")
	public Integer getPlanEducacion() {
		return this.planEducacion;
	}

	public void setPlanEducacion(Integer planEducacion) {
		this.planEducacion = planEducacion;
	}

	@Column(name = "plan_proyecto")
	public Integer getPlanProyecto() {
		return this.planProyecto;
	}

	public void setPlanProyecto(Integer planProyecto) {
		this.planProyecto = planProyecto;
	}

	@Column(name = "plan_jubilacion")
	public Integer getPlanJubilacion() {
		return this.planJubilacion;
	}

	public void setPlanJubilacion(Integer planJubilacion) {
		this.planJubilacion = planJubilacion;
	}

	@Column(name = "ingreso_titular", precision = 10)
	public Float getIngresoTitular() {
		return this.ingresoTitular;
	}

	public void setIngresoTitular(Float ingresoTitular) {
		this.ingresoTitular = ingresoTitular;
	}

	@Column(name = "porcentaje_inversion", precision = 4)
	public Float getPorcentajeInversion() {
		return this.porcentajeInversion;
	}

	public void setPorcentajeInversion(Float porcentajeInversion) {
		this.porcentajeInversion = porcentajeInversion;
	}

	@Column(name = "total_inversion", precision = 10)
	public Float getTotalInversion() {
		return this.totalInversion;
	}

	public void setTotalInversion(Float totalInversion) {
		this.totalInversion = totalInversion;
	}

	@Column(name = "anios_proteger")
	public Integer getAniosProteger() {
		return this.aniosProteger;
	}

	public void setAniosProteger(Integer aniosProteger) {
		this.aniosProteger = aniosProteger;
	}

	@Column(name = "respaldo_ahorros", precision = 10)
	public Float getRespaldoAhorros() {
		return this.respaldoAhorros;
	}

	public void setRespaldoAhorros(Float respaldoAhorros) {
		this.respaldoAhorros = respaldoAhorros;
	}

	@Column(name = "respaldo_ahorros_check")
	public Integer getRespaldoAhorrosCheck() {
		return this.respaldoAhorrosCheck;
	}

	public void setRespaldoAhorrosCheck(Integer respaldoAhorrosCheck) {
		this.respaldoAhorrosCheck = respaldoAhorrosCheck;
	}

	@Column(name = "respaldo_propiedades", precision = 10)
	public Float getRespaldoPropiedades() {
		return this.respaldoPropiedades;
	}

	public void setRespaldoPropiedades(Float respaldoPropiedades) {
		this.respaldoPropiedades = respaldoPropiedades;
	}

	@Column(name = "respaldo_propiedades_check")
	public Integer getRespaldoPropiedadesCheck() {
		return this.respaldoPropiedadesCheck;
	}

	public void setRespaldoPropiedadesCheck(Integer respaldoPropiedadesCheck) {
		this.respaldoPropiedadesCheck = respaldoPropiedadesCheck;
	}

	@Column(name = "respaldo_vehiculos", precision = 10)
	public Float getRespaldoVehiculos() {
		return this.respaldoVehiculos;
	}

	public void setRespaldoVehiculos(Float respaldoVehiculos) {
		this.respaldoVehiculos = respaldoVehiculos;
	}

	@Column(name = "respaldo_vehiculos_check")
	public Integer getRespaldoVehiculosCheck() {
		return this.respaldoVehiculosCheck;
	}

	public void setRespaldoVehiculosCheck(Integer respaldoVehiculosCheck) {
		this.respaldoVehiculosCheck = respaldoVehiculosCheck;
	}

	@Column(name = "respaldo_seguro_vida", precision = 10)
	public Float getRespaldoSeguroVida() {
		return this.respaldoSeguroVida;
	}

	public void setRespaldoSeguroVida(Float respaldoSeguroVida) {
		this.respaldoSeguroVida = respaldoSeguroVida;
	}

	@Column(name = "respaldo_seguro_vida_check")
	public Integer getRespaldoSeguroVidaCheck() {
		return this.respaldoSeguroVidaCheck;
	}

	public void setRespaldoSeguroVidaCheck(Integer respaldoSeguroVidaCheck) {
		this.respaldoSeguroVidaCheck = respaldoSeguroVidaCheck;
	}

	@Column(name = "respaldo_seguro_vida_ley", precision = 10)
	public Float getRespaldoSeguroVidaLey() {
		return this.respaldoSeguroVidaLey;
	}

	public void setRespaldoSeguroVidaLey(Float respaldoSeguroVidaLey) {
		this.respaldoSeguroVidaLey = respaldoSeguroVidaLey;
	}

	@Column(name = "respaldo_seguro_vida_ley_check")
	public Integer getRespaldoSeguroVidaLeyCheck() {
		return this.respaldoSeguroVidaLeyCheck;
	}

	public void setRespaldoSeguroVidaLeyCheck(Integer respaldoSeguroVidaLeyCheck) {
		this.respaldoSeguroVidaLeyCheck = respaldoSeguroVidaLeyCheck;
	}

	@Column(name = "capital_proteccion", precision = 10)
	public Float getCapitalProteccion() {
		return this.capitalProteccion;
	}

	public void setCapitalProteccion(Float capitalProteccion) {
		this.capitalProteccion = capitalProteccion;
	}

	@Column(name = "capital_respaldo", precision = 10)
	public Float getCapitalRespaldo() {
		return this.capitalRespaldo;
	}

	public void setCapitalRespaldo(Float capitalRespaldo) {
		this.capitalRespaldo = capitalRespaldo;
	}

	@Column(name = "capital_afp", precision = 10)
	public Float getCapitalAfp() {
		return this.capitalAfp;
	}

	public void setCapitalAfp(Float capitalAfp) {
		this.capitalAfp = capitalAfp;
	}

	@Column(name = "capital_afp_check")
	public Integer getCapitalAfpCheck() {
		return this.capitalAfpCheck;
	}

	public void setCapitalAfpCheck(Integer capitalAfpCheck) {
		this.capitalAfpCheck = capitalAfpCheck;
	}

	@Column(name = "capital_total_proteger", precision = 10)
	public Float getCapitalTotalProteger() {
		return this.capitalTotalProteger;
	}

	public void setCapitalTotalProteger(Float capitalTotalProteger) {
		this.capitalTotalProteger = capitalTotalProteger;
	}

	@Column(name = "capital_adicional", precision = 10)
	public Float getCapitalAdicional() {
		return this.capitalAdicional;
	}

	public void setCapitalAdicional(Float capitalAdicional) {
		this.capitalAdicional = capitalAdicional;
	}

	@Column(name = "capital_total_proteger_nuevo", precision = 10)
	public Float getCapitalTotalProtegerNuevo() {
		return this.capitalTotalProtegerNuevo;
	}

	public void setCapitalTotalProtegerNuevo(Float capitalTotalProtegerNuevo) {
		this.capitalTotalProtegerNuevo = capitalTotalProtegerNuevo;
	}

	@Column(name = "usuario_crea", nullable = false, length = 50)
	public String getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(String usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_crea", nullable = false, length = 19)
	public Date getFechaCrea() {
		return this.fechaCrea;
	}

	public void setFechaCrea(Date fechaCrea) {
		this.fechaCrea = fechaCrea;
	}

	@Column(name = "usuario_modif", length = 50)
	public String getUsuarioModif() {
		return this.usuarioModif;
	}

	public void setUsuarioModif(String usuarioModif) {
		this.usuarioModif = usuarioModif;
	}

	@Column(name = "fecha_modif", length = 45)
	public String getFechaModif() {
		return this.fechaModif;
	}

	public void setFechaModif(String fechaModif) {
		this.fechaModif = fechaModif;
	}

	@Column(name = "informacion_adicional", length = 200)
	public String getInformacionAdicional() {
		return informacionAdicional;
	}

	public void setInformacionAdicional(String informacionAdicional) {
		this.informacionAdicional = informacionAdicional;
	}

}
