package pe.interseguro.siv.common.persistence.db.mysql.domain;
// Generated oct 26, 2021 12:53:31 p.m. by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Poliza generated by hbm2java
 */
@Entity
@Table(name="poliza"
    ,catalog="siv_db"
)
public class Poliza  implements java.io.Serializable {


     private Integer idpoliza;
     private String tipoDocumento;
     private String numeroDocumento;
     private String numeroPoliza;
     private String fechaEmision;
     private String nombreProducto;
     private String estadoPoliza;
     private String pagadoHasta;
     private String moneda;
     private String montoCobertura;
     private String vidaAdicional;

    public Poliza() {
    }

	
    public Poliza(String tipoDocumento, String numeroDocumento, String numeroPoliza) {
        this.tipoDocumento = tipoDocumento;
        this.numeroDocumento = numeroDocumento;
        this.numeroPoliza = numeroPoliza;
    }
    public Poliza(String tipoDocumento, String numeroDocumento, String numeroPoliza, String fechaEmision, String nombreProducto, String estadoPoliza, String pagadoHasta, String moneda, String montoCobertura, String vidaAdicional) {
       this.tipoDocumento = tipoDocumento;
       this.numeroDocumento = numeroDocumento;
       this.numeroPoliza = numeroPoliza;
       this.fechaEmision = fechaEmision;
       this.nombreProducto = nombreProducto;
       this.estadoPoliza = estadoPoliza;
       this.pagadoHasta = pagadoHasta;
       this.moneda = moneda;
       this.montoCobertura = montoCobertura;
       this.vidaAdicional = vidaAdicional;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idpoliza", unique=true, nullable=false)
    public Integer getIdpoliza() {
        return this.idpoliza;
    }
    
    public void setIdpoliza(Integer idpoliza) {
        this.idpoliza = idpoliza;
    }

    
    @Column(name="tipoDocumento", nullable=false, length=45)
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }

    
    @Column(name="numeroDocumento", nullable=false, length=45)
    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }

    
    @Column(name="numeroPoliza", nullable=false, length=45)
    public String getNumeroPoliza() {
        return this.numeroPoliza;
    }
    
    public void setNumeroPoliza(String numeroPoliza) {
        this.numeroPoliza = numeroPoliza;
    }

    
    @Column(name="fechaEmision", length=45)
    public String getFechaEmision() {
        return this.fechaEmision;
    }
    
    public void setFechaEmision(String fechaEmision) {
        this.fechaEmision = fechaEmision;
    }

    
    @Column(name="nombreProducto", length=45)
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }

    
    @Column(name="estadoPoliza", length=45)
    public String getEstadoPoliza() {
        return this.estadoPoliza;
    }
    
    public void setEstadoPoliza(String estadoPoliza) {
        this.estadoPoliza = estadoPoliza;
    }

    
    @Column(name="pagadoHasta", length=45)
    public String getPagadoHasta() {
        return this.pagadoHasta;
    }
    
    public void setPagadoHasta(String pagadoHasta) {
        this.pagadoHasta = pagadoHasta;
    }

    
    @Column(name="moneda", length=45)
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }

    
    @Column(name="montoCobertura", length=45)
    public String getMontoCobertura() {
        return this.montoCobertura;
    }
    
    public void setMontoCobertura(String montoCobertura) {
        this.montoCobertura = montoCobertura;
    }

    
    @Column(name="vidaAdicional", length=45)
    public String getVidaAdicional() {
        return this.vidaAdicional;
    }
    
    public void setVidaAdicional(String vidaAdicional) {
        this.vidaAdicional = vidaAdicional;
    }




}


