package pe.interseguro.siv.common.persistence.db.mysql.domain;
// Generated May 20, 2019 8:07:22 PM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Multitabla generated by hbm2java
 */
@Entity
@Table(name = "servicio_edn", catalog = "siv_db")
public class ServicioEdn implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 921591234369905084L;
	private Long id_edn;
	private String solicitud;
	private String flag_edn;
	private String request;
	private String response;
	private String usuario_crea;
	private Date fecha_crea;
	private String usuario_modif;
	private Date fecha_modif;
	
	
	
	public ServicioEdn() {		
	}
	
	public ServicioEdn(Long id, String solicitud, String flag_edn, String request, String response,
			String usuario_crea, Date fecha_crea, String usuario_modif, Date fecha_modif) {		
		this.id_edn = id;
		this.solicitud = solicitud;
		this.flag_edn = flag_edn;
		this.request = request;
		this.response = response;
		this.usuario_crea = usuario_crea;
		this.fecha_crea = fecha_crea;
		this.usuario_modif = usuario_modif;
		this.fecha_modif = fecha_modif;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_edn", unique = true, nullable = false)
	public Long getId() {
		return id_edn;
	}	
	public void setId(Long id) {
		this.id_edn = id;
	}
	
	@Column(name = "solicitud", nullable = false, length = 20)
	public String getSolicitud() {
		return solicitud;
	}
	public void setSolicitud(String solicitud) {
		this.solicitud = solicitud;
	}
	
	@Column(name = "flag_edn", nullable = false, length = 1)
	public String getFlag_edn() {
		return flag_edn;
	}
	public void setFlag_edn(String flag_edn) {
		this.flag_edn = flag_edn;
	}
	
	@Column(name = "request", nullable = false, length = 200)
	public String getRequest() {
		return request;
	}
	public void setRequest(String request) {
		this.request = request;
	}
	
	@Column(name = "response", length = 200)
	public String getResponse() {
		return response;
	}
	public void setResponse(String response) {
		this.response = response;
	}
	
	@Column(name = "usuario_crea", nullable = false, length = 50)
	public String getUsuario_crea() {
		return usuario_crea;
	}
	public void setUsuario_crea(String usuario_crea) {
		this.usuario_crea = usuario_crea;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_crea", nullable = false, length = 19)
	public Date getFecha_crea() {
		return fecha_crea;
	}
	public void setFecha_crea(Date fecha_crea) {
		this.fecha_crea = fecha_crea;
	}
	
	@Column(name = "usuario_modif", length = 50)
	public String getUsuario_modif() {
		return usuario_modif;
	}
	public void setUsuario_modif(String usuario_modif) {
		this.usuario_modif = usuario_modif;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modif", length = 19)
	public Date getFecha_modif() {
		return fecha_modif;
	}
	public void setFecha_modif(Date fecha_modif) {
		this.fecha_modif = fecha_modif;
	}	
	
}
