package pe.interseguro.siv.common.persistence.db.mysql.domain;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SolicitudViaCobro generated by hbm2java
 */
@Entity
@Table(name = "solicitud_via_cobro", catalog = "siv_db")
public class SolicitudViaCobro implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 762842539955794450L;
	private Integer idViaCobro;
	private Integer tipoViaCobro;
	private Integer codigoViaCobro;
	private String nombreViaCobro;
	private String tipoCuenta;
	private String mascara;
	private Integer longitud;
	private Integer ccv;
	private String usuarioCreacion;
	private Date fechaCreacion;
	private String usuarioModificacion;
	private Date fechaModificacion;
	
	public SolicitudViaCobro() {}
	
	public SolicitudViaCobro(Integer tipoViaCobro, Integer codigoViaCobro, String nombreViaCobro,String tipoCuenta,String mascara,Integer longitud, 
			String usuarioCreacion,Date fechaCreacion,String usuarioModificacion,Date fechaModificacion) {
		this.tipoViaCobro = tipoViaCobro;
		this.codigoViaCobro = codigoViaCobro;
		this.nombreViaCobro = nombreViaCobro;
		this.tipoCuenta = tipoCuenta;
		this.mascara = mascara;
		this.longitud = longitud;
		this.usuarioCreacion = usuarioCreacion;
		this.fechaCreacion = fechaCreacion;
		this.usuarioModificacion = usuarioModificacion;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_via_cobro", unique = true, nullable = false)
	public Integer getIdViaCobro() {
		return idViaCobro;
	}

	public void setIdViaCobro(Integer idViaCobro) {
		this.idViaCobro = idViaCobro;
	}

	@Column(name = "tipo_via_cobro", nullable = false)
	public Integer getTipoViaCobro() {
		return tipoViaCobro;
	}

	public void setTipoViaCobro(Integer tipoViaCobro) {
		this.tipoViaCobro = tipoViaCobro;
	}

	@Column(name = "nombre_via_cobro", nullable = false)
	public String getNombreViaCobro() {
		return nombreViaCobro;
	}

	public void setNombreViaCobro(String nombreViaCobro) {
		this.nombreViaCobro = nombreViaCobro;
	}

	@Column(name = "tipo_cuenta", nullable = false)
	public String getTipoCuenta() {
		return tipoCuenta;
	}

	public void setTipoCuenta(String tipoCuenta) {
		this.tipoCuenta = tipoCuenta;
	}

	@Column(name = "mascara", nullable = false)
	public String getMascara() {
		return mascara;
	}

	public void setMascara(String mascara) {
		this.mascara = mascara;
	}

	@Column(name = "longitud", nullable = false)
	public Integer getLongitud() {
		return longitud;
	}

	public void setLongitud(Integer longitud) {
		this.longitud = longitud;
	}

	@Column(name = "usuario_crea", nullable = false)
	public String getUsuarioCreacion() {
		return usuarioCreacion;
	}

	public void setUsuarioCreacion(String usuarioCreacion) {
		this.usuarioCreacion = usuarioCreacion;
	}

	@Column(name = "fecha_crea", nullable = false)
	public Date getFechaCreacion() {
		return fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "usuario_modif")
	public String getUsuarioModificacion() {
		return usuarioModificacion;
	}

	public void setUsuarioModificacion(String usuarioModificacion) {
		this.usuarioModificacion = usuarioModificacion;
	}

	@Column(name = "fecha_modif")
	public Date getFechaModificacion() {
		return fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "codigo_via_cobro", nullable = false)
	public Integer getCodigoViaCobro() {
		return codigoViaCobro;
	}

	public void setCodigoViaCobro(Integer codigoViaCobro) {
		this.codigoViaCobro = codigoViaCobro;
	}

	@Column(name = "ccv", nullable = false)
	public Integer getCcv() {
		return ccv;
	}

	public void setCcv(Integer ccv) {
		this.ccv = ccv;
	}

}
