package pe.interseguro.siv.common.persistence.db.mysql.domain;
// Generated 10/09/2019 04:43:02 PM by Hibernate Tools 4.3.2-SNAPSHOT

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.ToString;


/**
 * Solicitud generated by hbm2java
 */
@Entity
@Table(name = "solicitud", catalog = "siv_db")
public class Solicitud implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8886937603136175901L;
	private Long idSolicitud;
	protected Long idAsegurado;
	protected Long idContratante;
	private Persona personaByIdContratante;
	private Persona personaByIdAsegurado;
	private String numeroCotizacion;
	private String numeroCotizacionOrigen;
	private String numeroPropuesta;
	private String numeroPoliza;
	private String aseguradoIgualContratante;
	private String vinculoAsegurado;
	private String jsonContratante;
	private String jsonBeneficiario;
	private String estado;
	private String estadoGeneral;
	private String estadoPlaft;
	private String subplan;
	private String moneda;
	private String idCircuitoFirma;
	private Integer tratamientoAseguradoCheck;
	private Integer tratamientoContratanteCheck;
	private Date fechaFirmaAsegurado;
	private Date fechaFirmaContratante;
	private String nombreArchivoSolicitud;
	private String idCrmOportunidad;
	private String idCrmCotizador;
	private String idCrmUsuario;
	private String agenteNombres;
	private String agenteCorreo;
	private String agenteNumVendedor;
	private Date fechaSolicitud;
	private String idPagoCulqi;
	private Date fechaPagoCulqi;
	private String idPagoNiubiz;
	private Date fechaPagoNiubiz;
	private String idAfiliacionPropuesta;
	private String idTarjetaSitc;
	private Integer idViaCobro;
	private Integer idCuenta;
	private String idCuentaMoneda;
	private Integer flagCrmSitc;
	private Date fechaAfiliacionPropuesta;
	private Date fechaRegistroSamp;
	private String tarjetaAfiliacion;
	private String tokenOnline;
	private String tokenTimeExpiry;
	private String tokenStatus;
	private String usuarioCrea;
	private Date fechaCrea;
	private String usuarioModif;
	private Date fechaModif;
	private Date fechaEmisoon;
	private Set<SolicitudBeneficiario> solicitudBeneficiarios = new HashSet<SolicitudBeneficiario>(0);
	private Set<SolicitudProducto> solicitudProductos = new HashSet<>(0);
	private Set<SolicitudDps> solicitudDpses = new HashSet<SolicitudDps>(0);
	private String requestCrm;
	private String pagoPrima;
	private String tokenAdnRecargo;
	private String tokenTimeRecargo;
	private String tokenStatusRecargo;
	private String purchaseNumber;
	private String estadoRecargo;
	private String idPagoNiubizRecargo;
	private Date fechaPagoNiubizRecargo;
	private String pagoPrimaRecargo;
	private String alertaPlaft;
	private String estadoTraspaso;
	private String idViaCobroPP;
	private String numeroTarjetaPP;
	private String idPagoCulqiRecargo;
	private Date fechaPagoCulqiRecargo;
	private Float montoRecargo;
	private String tokenAfiliacion;
	private String documentoAcp;
	private String documentoCotizacion;
	private String flagExclusionCobAcc;
	private Integer estadoPropuesta;
	private String idPlan;
	private String nombrePlan;
	
	private String documentoSolicitud;
	private String documentoEdn;
	private String flgProcesoEmision;
	private String estadoPubSubSend;
	// Mixpasarelas - Izipay
	private String idPagoIzipay;
	private Date fechaPagoIzipay;

	public Solicitud() {
	}

	public Solicitud(Persona personaByIdAsegurado, String numeroCotizacion, String estado, String usuarioCrea,
			Date fechaCrea) {
		this.personaByIdAsegurado = personaByIdAsegurado;
		this.numeroCotizacion = numeroCotizacion;
		this.estado = estado;
		this.usuarioCrea = usuarioCrea;
		this.fechaCrea = fechaCrea;
	}

	public Solicitud(Persona personaByIdContratante, Persona personaByIdAsegurado, String numeroCotizacion,
			String numeroPropuesta, String numeroPoliza, String aseguradoIgualContratante, String vinculoAsegurado,
			String jsonContratante, String jsonBeneficiario, String estado, String subplan, String moneda,
			String idCircuitoFirma, Integer tratamientoAseguradoCheck, Integer tratamientoContratanteCheck,
			Date fechaFirmaAsegurado, Date fechaFirmaContratante, String nombreArchivoSolicitud,
			String idCrmOportunidad, String idCrmCotizador, String idCrmUsuario, String agenteNombres,
			String agenteNumVendedor, String agenteCorreo, Date fechaSolicitud, String usuarioCrea, Date fechaCrea,
			String usuarioModif, Date fechaModif, Set<SolicitudBeneficiario> solicitudBeneficiarios,
			Set<SolicitudProducto> solicitudProductos, Set<SolicitudDps> solicitudDpses, String requestCrm,
			String pagoPrima, String tokenAdnRecargo, String tokenTimeRecargo, String tokenStatusRecargo,
			String purchaseNumber, String estadoRecargo, String idPagoNiubizRecargo, Date fechaPagoNiubizRecargo,
			String pagoPrimaRecargo, String alertaPlaft, String estadoTraspaso, String idViaCobroPP, String numeroTarjetaPP, Date fechaPagoCulqiRecargo,
			String idPagoCulqiRecargo , Float montoRecargo,String tokenAfiliacion,String documentoAcp,String documentoCotizacion,
			String documentoSolicitud,String documentoEdn,String flgProcesoEmision,String estadoPubSubSend, String flagExclusionCobAcc, Date fechaEmisoon) {
		this.personaByIdContratante = personaByIdContratante;
		this.personaByIdAsegurado = personaByIdAsegurado;
		this.numeroCotizacion = numeroCotizacion;
		this.numeroPropuesta = numeroPropuesta;
		this.numeroPoliza = numeroPoliza;
		this.aseguradoIgualContratante = aseguradoIgualContratante;
		this.vinculoAsegurado = vinculoAsegurado;
		this.jsonContratante = jsonContratante;
		this.jsonBeneficiario = jsonBeneficiario;
		this.estado = estado;
		this.estadoGeneral = estadoGeneral;
		this.estadoPlaft = estadoPlaft;
		this.subplan = subplan;
		this.moneda = moneda;
		this.idCircuitoFirma = idCircuitoFirma;
		this.tratamientoAseguradoCheck = tratamientoAseguradoCheck;
		this.tratamientoContratanteCheck = tratamientoContratanteCheck;
		this.fechaFirmaAsegurado = fechaFirmaAsegurado;
		this.fechaFirmaContratante = fechaFirmaContratante;
		this.nombreArchivoSolicitud = nombreArchivoSolicitud;
		this.idCrmOportunidad = idCrmOportunidad;
		this.idCrmCotizador = idCrmCotizador;
		this.idCrmUsuario = idCrmUsuario;
		this.agenteNombres = agenteNombres;
		this.agenteNumVendedor = agenteNumVendedor;
		this.agenteCorreo = agenteCorreo;
		this.fechaSolicitud = fechaSolicitud;
		this.usuarioCrea = usuarioCrea;
		this.fechaCrea = fechaCrea;
		this.usuarioModif = usuarioModif;
		this.fechaModif = fechaModif;
		this.fechaEmisoon = fechaEmisoon;
		this.solicitudBeneficiarios = solicitudBeneficiarios;
		this.solicitudProductos = solicitudProductos;
		this.solicitudDpses = solicitudDpses;
		this.requestCrm = requestCrm;
		this.pagoPrima = pagoPrima;
		this.tokenAdnRecargo = tokenAdnRecargo;
		this.tokenTimeRecargo = tokenTimeRecargo;
		this.tokenStatusRecargo = tokenStatusRecargo;

		this.estadoRecargo = estadoRecargo;
		this.idPagoNiubizRecargo = idPagoNiubizRecargo;
		this.idPagoCulqiRecargo = idPagoCulqiRecargo;
		this.fechaPagoNiubizRecargo = fechaPagoNiubizRecargo;
		this.pagoPrimaRecargo = pagoPrimaRecargo;
		this.alertaPlaft = alertaPlaft;
		this.estadoTraspaso = estadoTraspaso;
		//this.pagoPrima = pagoPrima;
		this.purchaseNumber = purchaseNumber;
		this.idViaCobroPP = idViaCobroPP;
		this.numeroTarjetaPP = numeroTarjetaPP;
		this.fechaPagoCulqiRecargo = fechaPagoCulqiRecargo;
		this.montoRecargo = montoRecargo;
		this.tokenAfiliacion= tokenAfiliacion;
		this.documentoAcp= documentoAcp;
		this.documentoCotizacion= documentoCotizacion;
		this.documentoSolicitud= documentoSolicitud;
		this.documentoEdn= documentoEdn;
		this.flgProcesoEmision= flgProcesoEmision;
		this.estadoPubSubSend= estadoPubSubSend;
		this.flagExclusionCobAcc = flagExclusionCobAcc;
		
	}

	public Solicitud(Persona personaByIdContratante, Persona personaByIdAsegurado, String numeroCotizacion,
			String numeroCotizacionOrigen, String numeroPropuesta, String numeroPoliza,
			String aseguradoIgualContratante, String vinculoAsegurado, String jsonContratante, String jsonBeneficiario,
			String estado, String subplan, String moneda, String idCircuitoFirma, Integer tratamientoAseguradoCheck,
			Integer tratamientoContratanteCheck, Date fechaFirmaAsegurado, Date fechaFirmaContratante,
			String nombreArchivoSolicitud, String idCrmOportunidad, String idCrmCotizador, String idCrmUsuario,
			String agenteNombres, String agenteNumVendedor, String agenteCorreo, Date fechaSolicitud,
			String usuarioCrea, Date fechaCrea, String usuarioModif, Date fechaModif,
			Set<SolicitudBeneficiario> solicitudBeneficiarios, Set<SolicitudProducto> solicitudProductos,
			Set<SolicitudDps> solicitudDpses) {
		this.personaByIdContratante = personaByIdContratante;
		this.personaByIdAsegurado = personaByIdAsegurado;
		this.numeroCotizacion = numeroCotizacion;
		this.numeroCotizacionOrigen = numeroCotizacionOrigen;
		this.numeroPropuesta = numeroPropuesta;
		this.numeroPoliza = numeroPoliza;
		this.aseguradoIgualContratante = aseguradoIgualContratante;
		this.vinculoAsegurado = vinculoAsegurado;
		this.jsonContratante = jsonContratante;
		this.jsonBeneficiario = jsonBeneficiario;
		this.estado = estado;
		this.estadoGeneral = estadoGeneral;
		this.estadoPlaft = estadoPlaft;
		this.subplan = subplan;
		this.moneda = moneda;
		this.idCircuitoFirma = idCircuitoFirma;
		this.tratamientoAseguradoCheck = tratamientoAseguradoCheck;
		this.tratamientoContratanteCheck = tratamientoContratanteCheck;
		this.fechaFirmaAsegurado = fechaFirmaAsegurado;
		this.fechaFirmaContratante = fechaFirmaContratante;
		this.nombreArchivoSolicitud = nombreArchivoSolicitud;
		this.idCrmOportunidad = idCrmOportunidad;
		this.idCrmCotizador = idCrmCotizador;
		this.idCrmUsuario = idCrmUsuario;
		this.agenteNombres = agenteNombres;
		this.agenteNumVendedor = agenteNumVendedor;
		this.agenteCorreo = agenteCorreo;
		this.fechaSolicitud = fechaSolicitud;
		this.usuarioCrea = usuarioCrea;
		this.fechaCrea = fechaCrea;
		this.usuarioModif = usuarioModif;
		this.fechaModif = fechaModif;
		this.solicitudBeneficiarios = solicitudBeneficiarios;
		this.solicitudProductos = solicitudProductos;
		this.solicitudDpses = solicitudDpses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_solicitud", unique = true, nullable = false)
	public Long getIdSolicitud() {
		return this.idSolicitud;
	}

	public void setIdSolicitud(Long idSolicitud) {
		this.idSolicitud = idSolicitud;
	}

	@Column(name = "id_asegurado", insertable = false, updatable = false)
	public Long getIdAsegurado() {
		return idAsegurado;
	}

	public void setIdAsegurado(Long idAsegurado) {
		this.idAsegurado = idAsegurado;
	}

	@Column(name = "id_contratante", insertable = false, updatable = false)
	public Long getIdContratante() {
		return idContratante;
	}

	public void setIdContratante(Long idContratante) {
		this.idContratante = idContratante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_contratante")
	public Persona getPersonaByIdContratante() {
		return this.personaByIdContratante;
	}

	public void setPersonaByIdContratante(Persona personaByIdContratante) {
		this.personaByIdContratante = personaByIdContratante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_asegurado", nullable = false)
	public Persona getPersonaByIdAsegurado() {
		return this.personaByIdAsegurado;
	}

	public void setPersonaByIdAsegurado(Persona personaByIdAsegurado) {
		this.personaByIdAsegurado = personaByIdAsegurado;
	}

	@Column(name = "numero_cotizacion", nullable = false, length = 20)
	public String getNumeroCotizacion() {
		return this.numeroCotizacion;
	}

	public void setNumeroCotizacion(String numeroCotizacion) {
		this.numeroCotizacion = numeroCotizacion;
	}

	@Column(name = "numero_cotizacion_origen", nullable = true, length = 20)
	public String getNumeroCotizacionOrigen() {
		return this.numeroCotizacionOrigen;
	}

	public void setNumeroCotizacionOrigen(String numeroCotizacionOrigen) {
		this.numeroCotizacionOrigen = numeroCotizacionOrigen;
	}

	@Column(name = "numero_propuesta", length = 20)
	public String getNumeroPropuesta() {
		return this.numeroPropuesta;
	}

	public void setNumeroPropuesta(String numeroPropuesta) {
		this.numeroPropuesta = numeroPropuesta;
	}

	@Column(name = "numero_poliza", length = 20)
	public String getNumeroPoliza() {
		return this.numeroPoliza;
	}

	public void setNumeroPoliza(String numeroPoliza) {
		this.numeroPoliza = numeroPoliza;
	}

	@Column(name = "asegurado_igual_contratante", length = 1)
	public String getAseguradoIgualContratante() {
		return this.aseguradoIgualContratante;
	}

	public void setAseguradoIgualContratante(String aseguradoIgualContratante) {
		this.aseguradoIgualContratante = aseguradoIgualContratante;
	}

	@Column(name = "vinculo_asegurado", length = 1)
	public String getVinculoAsegurado() {
		return this.vinculoAsegurado;
	}

	public void setVinculoAsegurado(String vinculoAsegurado) {
		this.vinculoAsegurado = vinculoAsegurado;
	}
	@Column(name = "json_contratante")
	public String getJsonContratante() {
		return this.jsonContratante;
	}

	public void setJsonContratante(String jsonContratante) {
		this.jsonContratante = jsonContratante;
	}

	@Column(name = "json_beneficiario")
	public String getJsonBeneficiario() {
		return this.jsonBeneficiario;
	}

	public void setJsonBeneficiario(String jsonBeneficiario) {
		this.jsonBeneficiario = jsonBeneficiario;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "estado_General", nullable = false, length = 1)
	public String getEstadoGeneral() {
		return this.estadoGeneral;
	}

	public void setEstadoGeneral(String estadoGeneral) {
		this.estadoGeneral = estadoGeneral;
	}

	@Column(name = "estado_plaft", nullable = false, length = 50)
	public String getEstadoPlaft() {
		return this.estadoPlaft;
	}

	public void setEstadoPlaft(String estadoPlaft) {
		this.estadoPlaft = estadoPlaft;
	}

	@Column(name = "subplan", length = 1)
	public String getSubplan() {
		return this.subplan;
	}

	public void setSubplan(String subplan) {
		this.subplan = subplan;
	}

	@Column(name = "moneda", length = 1)
	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	@Column(name = "id_circuito_firma", length = 10)
	public String getIdCircuitoFirma() {
		return this.idCircuitoFirma;
	}

	public void setIdCircuitoFirma(String idCircuitoFirma) {
		this.idCircuitoFirma = idCircuitoFirma;
	}

	@Column(name = "tratamiento_asegurado_check")
	public Integer getTratamientoAseguradoCheck() {
		return this.tratamientoAseguradoCheck;
	}

	public void setTratamientoAseguradoCheck(Integer tratamientoAseguradoCheck) {
		this.tratamientoAseguradoCheck = tratamientoAseguradoCheck;
	}

	@Column(name = "tratamiento_contratante_check")
	public Integer getTratamientoContratanteCheck() {
		return this.tratamientoContratanteCheck;
	}

	public void setTratamientoContratanteCheck(Integer tratamientoContratanteCheck) {
		this.tratamientoContratanteCheck = tratamientoContratanteCheck;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_firma_asegurado", length = 19)
	public Date getFechaFirmaAsegurado() {
		return this.fechaFirmaAsegurado;
	}

	public void setFechaFirmaAsegurado(Date fechaFirmaAsegurado) {
		this.fechaFirmaAsegurado = fechaFirmaAsegurado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_firma_contratante", length = 19)
	public Date getFechaFirmaContratante() {
		return this.fechaFirmaContratante;
	}

	public void setFechaFirmaContratante(Date fechaFirmaContratante) {
		this.fechaFirmaContratante = fechaFirmaContratante;
	}

	@Column(name = "nombre_archivo_solicitud", length = 50)
	public String getNombreArchivoSolicitud() {
		return this.nombreArchivoSolicitud;
	}

	public void setNombreArchivoSolicitud(String nombreArchivoSolicitud) {
		this.nombreArchivoSolicitud = nombreArchivoSolicitud;
	}

	@Column(name = "id_crm_oportunidad", length = 40)
	public String getIdCrmOportunidad() {
		return this.idCrmOportunidad;
	}

	public void setIdCrmOportunidad(String idCrmOportunidad) {
		this.idCrmOportunidad = idCrmOportunidad;
	}

	@Column(name = "id_crm_cotizador", length = 40)
	public String getIdCrmCotizador() {
		return this.idCrmCotizador;
	}

	public void setIdCrmCotizador(String idCrmCotizador) {
		this.idCrmCotizador = idCrmCotizador;
	}

	@Column(name = "id_crm_usuario", length = 40)
	public String getIdCrmUsuario() {
		return this.idCrmUsuario;
	}

	public void setIdCrmUsuario(String idCrmUsuario) {
		this.idCrmUsuario = idCrmUsuario;
	}

	@Column(name = "agente_nombres", length = 150)
	public String getAgenteNombres() {
		return this.agenteNombres;
	}

	public void setAgenteNombres(String agenteNombres) {
		this.agenteNombres = agenteNombres;
	}

	@Column(name = "agente_correo", length = 150)
	public String getAgenteCorreo() {
		return agenteCorreo;
	}

	public void setAgenteCorreo(String agenteCorreo) {
		this.agenteCorreo = agenteCorreo;
	}

	@Column(name = "agente_num_vendedor", length = 20)
	public String getAgenteNumVendedor() {
		return this.agenteNumVendedor;
	}

	public void setAgenteNumVendedor(String agenteNumVendedor) {
		this.agenteNumVendedor = agenteNumVendedor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_solicitud", length = 19)
	public Date getFechaSolicitud() {
		return this.fechaSolicitud;
	}

	public void setFechaSolicitud(Date fechaSolicitud) {
		this.fechaSolicitud = fechaSolicitud;
	}

	@Column(name = "usuario_crea", nullable = false, length = 50)
	public String getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(String usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_crea", nullable = false, length = 19)
	public Date getFechaCrea() {
		return this.fechaCrea;
	}

	public void setFechaCrea(Date fechaCrea) {
		this.fechaCrea = fechaCrea;
	}

	@Column(name = "usuario_modif", length = 50)
	public String getUsuarioModif() {
		return this.usuarioModif;
	}

	public void setUsuarioModif(String usuarioModif) {
		this.usuarioModif = usuarioModif;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modif", length = 19)
	public Date getFechaModif() {
		return this.fechaModif;
	}

	public void setFechaModif(Date fechaModif) {
		this.fechaModif = fechaModif;
	}
	
	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitud")
	public Set<SolicitudBeneficiario> getSolicitudBeneficiarios() {
		return this.solicitudBeneficiarios;
	}

	public void setSolicitudBeneficiarios(Set<SolicitudBeneficiario> solicitudBeneficiarios) {
		this.solicitudBeneficiarios = solicitudBeneficiarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitud")
	public Set<SolicitudProducto> getSolicitudProductos() {
		return this.solicitudProductos;
	}

	public void setSolicitudProductos(Set<SolicitudProducto> solicitudProductos) {
		this.solicitudProductos = solicitudProductos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitud")
	public Set<SolicitudDps> getSolicitudDpses() {
		return this.solicitudDpses;
	}

	public void setSolicitudDpses(Set<SolicitudDps> solicitudDpses) {
		this.solicitudDpses = solicitudDpses;
	}

	@Column(name = "id_pago_culqi", length = 100)
	public String getIdPagoCulqi() {
		return idPagoCulqi;
	}

	public void setIdPagoCulqi(String idPagoCulqi) {
		this.idPagoCulqi = idPagoCulqi;
	}

	@Column(name = "id_pago_niubiz", length = 100)
	public String getIdPagoNiubiz() {
		return idPagoNiubiz;
	}

	public void setIdPagoNiubiz(String idPagoNiubiz) {
		this.idPagoNiubiz = idPagoNiubiz;
	}

	@Column(name = "id_afiliacion", length = 20)
	public String getIdAfiliacionPropuesta() {
		return idAfiliacionPropuesta;
	}

	public void setIdAfiliacionPropuesta(String idAfiliacionPropuesta) {
		this.idAfiliacionPropuesta = idAfiliacionPropuesta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_pago_culqi", length = 19)
	public Date getFechaPagoCulqi() {
		return fechaPagoCulqi;
	}

	public void setFechaPagoCulqi(Date fechaPagoCulqi) {
		this.fechaPagoCulqi = fechaPagoCulqi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_pago_niubiz", length = 19)
	public Date getFechaPagoNiubiz() {
		return fechaPagoNiubiz;
	}

	public void setFechaPagoNiubiz(Date fechaPagoNiubiz) {
		this.fechaPagoNiubiz = fechaPagoNiubiz;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_afiliacion", length = 19)
	public Date getFechaAfiliacionPropuesta() {
		return fechaAfiliacionPropuesta;
	}

	public void setFechaAfiliacionPropuesta(Date fechaAfiliacionPropuesta) {
		this.fechaAfiliacionPropuesta = fechaAfiliacionPropuesta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_samp", length = 19)
	public Date getFechaRegistroSamp() {
		return fechaRegistroSamp;
	}

	public void setFechaRegistroSamp(Date fechaRegistroSamp) {
		this.fechaRegistroSamp = fechaRegistroSamp;
	}

	@Column(name = "tarjeta_afiliacion")
	public String getTarjetaAfiliacion() {
		return this.tarjetaAfiliacion;
	}

	public void setTarjetaAfiliacion(String tarjetaAfiliacion) {
		this.tarjetaAfiliacion = tarjetaAfiliacion;
	}

	@Column(name = "id_via_cobro")
	public Integer getIdViaCobro() {
		return idViaCobro;
	}

	public void setIdViaCobro(Integer idViaCobro) {
		this.idViaCobro = idViaCobro;
	}

	@Column(name = "flag_crm_sitc")
	public Integer getFlagCrmSitc() {
		return flagCrmSitc;
	}

	public void setFlagCrmSitc(Integer flagCrmSitc) {
		this.flagCrmSitc = flagCrmSitc;
	}

	@Column(name = "id_tarjeta_sitc")
	public String getIdTarjetaSitc() {
		return idTarjetaSitc;
	}

	public void setIdTarjetaSitc(String idTarjetaSitc) {
		this.idTarjetaSitc = idTarjetaSitc;
	}

	@Column(name = "token_online")
	public String getTokenOnline() {
		return tokenOnline;
	}

	public void setTokenOnline(String tokenOnline) {
		this.tokenOnline = tokenOnline;
	}

	@Column(name = "token_time")
	public String getTokenTimeExpiry() {
		return tokenTimeExpiry;
	}

	public void setTokenTimeExpiry(String tokenTimeExpiry) {
		this.tokenTimeExpiry = tokenTimeExpiry;
	}

	@Column(name = "token_status")
	public String getTokenStatus() {
		return tokenStatus;
	}

	public void setTokenStatus(String tokenStatus) {
		this.tokenStatus = tokenStatus;
	}

	@Column(name = "id_cuenta")
	public Integer getIdCuenta() {
		return idCuenta;
	}

	public void setIdCuenta(Integer idCuenta) {
		this.idCuenta = idCuenta;
	}

	@Column(name = "id_cuenta_moneda")
	public String getIdCuentaMoneda() {
		return idCuentaMoneda;
	}

	public void setIdCuentaMoneda(String idCuentaMoneda) {
		this.idCuentaMoneda = idCuentaMoneda;
	}

	@Column(name = "request_crm", length = 6000)
	public String getRequestCrm() {
		return requestCrm;
	}

	public void setRequestCrm(String requestCrm) {
		this.requestCrm = requestCrm;
	}

	@Column(name = "pago_prima", length = 1)
	public String getPagoPrima() {
		return pagoPrima;
	}

	public void setPagoPrima(String pagoPrima) {
		this.pagoPrima = pagoPrima;
	}

	@Column(name = "token_adn_recargo", length = 2000)
	public String getTokenAdnRecargo() {
		return this.tokenAdnRecargo;
	}

	public void setTokenAdnRecargo(String tokenAdnRecargo) {
		this.tokenAdnRecargo = tokenAdnRecargo;
	}

	@Column(name = "token_time_recargo", length = 50)
	public String getTokenTimeRecargo() {
		return this.tokenTimeRecargo;
	}

	public void setTokenTimeRecargo(String tokenTimeRecargo) {
		this.tokenTimeRecargo = tokenTimeRecargo;
	}

	@Column(name = "token_status_recargo", length = 1)
	public String getTokenStatusRecargo() {
		return this.tokenStatusRecargo;
	}

	public void setTokenStatusRecargo(String tokenStatusRecargo) {
		this.tokenStatusRecargo = tokenStatusRecargo;
	}

	@Column(name = "purchase_number", length = 10)
	public String getPurchaseNumber() {
		return purchaseNumber;
	}

	public void setPurchaseNumber(String purchaseNumber) {
		this.purchaseNumber = purchaseNumber;
	}

	@Column(name = "estado_recargo", length = 1)
	public String getEstadoRecargo() {
		return this.estadoRecargo;
	}

	public void setEstadoRecargo(String estadoRecargo) {
		this.estadoRecargo = estadoRecargo;
	}

	@Column(name = "id_pago_niubiz_recargo", length = 100)
	public String getIdPagoNiubizRecargo() {
		return this.idPagoNiubizRecargo;
	}

	public void setIdPagoNiubizRecargo(String idPagoNiubizRecargo) {
		this.idPagoNiubizRecargo = idPagoNiubizRecargo;
	}

	@Column(name="estado_traspaso", length=1)
	    public String getEstadoTraspaso() {
	        return this.estadoTraspaso;
	    }
	    
	    public void setEstadoTraspaso(String estadoTraspaso) {
	        this.estadoTraspaso = estadoTraspaso;
	    }
		
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_pago_niubiz_recargo", length = 19)
	public Date getFechaPagoNiubizRecargo() {
		return this.fechaPagoNiubizRecargo;
	}

	public void setFechaPagoNiubizRecargo(Date fechaPagoNiubizRecargo) {
		this.fechaPagoNiubizRecargo = fechaPagoNiubizRecargo;
	}

	@Column(name = "pago_prima_recargo", length = 1)
	public String getPagoPrimaRecargo() {
		return this.pagoPrimaRecargo;
	}

	public void setPagoPrimaRecargo(String pagoPrimaRecargo) {
		this.pagoPrimaRecargo = pagoPrimaRecargo;
	}

	@Column(name = "alerta_plaft", length = 10)
	public String getAlertaPlaft() {
		return this.alertaPlaft;
	}

	public void setAlertaPlaft(String alertaPlaft) {
		this.alertaPlaft = alertaPlaft;
	}

	@Column(name = "id_via_cobro_pp", length = 2)
	public String getIdViaCobroPP() {
		return idViaCobroPP;
	}

	public void setIdViaCobroPP(String idViaCobroPP) {
		this.idViaCobroPP = idViaCobroPP;
	}

	@Column(name = "numero_tarjeta_pp", length = 30)
	public String getNumeroTarjetaPP() {
		return numeroTarjetaPP;
	}

	public void setNumeroTarjetaPP(String numeroTarjetaPP) {
		this.numeroTarjetaPP = numeroTarjetaPP;
	}
	
	@Column(name="id_pago_culqi_recargo", length=100)
    public String getIdPagoCulqiRecargo() {
        return this.idPagoCulqiRecargo;
    }
    
    public void setIdPagoCulqiRecargo(String idPagoCulqiRecargo) {
        this.idPagoCulqiRecargo = idPagoCulqiRecargo;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_pago_culqi_recargo", length=19)
    public Date getFechaPagoCulqiRecargo() {
        return this.fechaPagoCulqiRecargo;
    }
    
    public void setFechaPagoCulqiRecargo(Date fechaPagoCulqiRecargo) {
        this.fechaPagoCulqiRecargo = fechaPagoCulqiRecargo;
    }
    
    @Column(name="monto_recargo", precision=10)
    public Float getMontoRecargo() {
        return this.montoRecargo;
    }
    
    public void setMontoRecargo(Float montoRecargo) {
        this.montoRecargo = montoRecargo;
    }
    
	@Column(name="token_afiliacion", precision=50)
	public String getTokenAfiliacion() {
		return tokenAfiliacion;
	}

	public void setTokenAfiliacion(String tokenAfiliacion) {
		this.tokenAfiliacion = tokenAfiliacion;
	}
	
	@Column(name = "documento_acp", length = 500)
	public String getDocumentoAcp() {
		return documentoAcp;
	}

	public void setDocumentoAcp(String documentoAcp) {
		this.documentoAcp = documentoAcp;
	}
	
	@Column(name = "documento_cotizacion", length = 500)
	public String getDocumentoCotizacion() {
		return documentoCotizacion;
	}

	public void setDocumentoCotizacion(String documentoCotizacion) {
		this.documentoCotizacion = documentoCotizacion;
	}
	
	@Column(name = "documento_solicitud", length = 500)
	public String getDocumentoSolicitud() {
		return documentoSolicitud;
	}

	public void setDocumentoSolicitud(String documentoSolicitud) {
		this.documentoSolicitud = documentoSolicitud;
	}
	
	@Column(name = "documento_edn", length = 500)
	public String getDocumentoEdn() {
		return documentoEdn;
	}

	public void setDocumentoEdn(String documentoEdn) {
		this.documentoEdn = documentoEdn;
	}
	
	@Column(name = "flg_proceso_emision", nullable = false, length = 1)
	public String getFlgProcesoEmision() {
		return flgProcesoEmision;
	}

	public void setFlgProcesoEmision(String flgProcesoEmision) {
		this.flgProcesoEmision = flgProcesoEmision;
	}
	
	@Column(name = "estado_pubsubsend", nullable = false, length = 1)
	public String getEstadoPubSubSend() {
		return estadoPubSubSend;
	}

	public void setEstadoPubSubSend(String estadoPubSubSend) {
		this.estadoPubSubSend = estadoPubSubSend;
	}
    
	@Column(name = "flag_exclusion_cob_acc", length = 1)
	public String getFlagExclusionCobAcc() {
		return this.flagExclusionCobAcc;
	}

	public void setFlagExclusionCobAcc(String flagExclusionCobAcc) {
		this.flagExclusionCobAcc = flagExclusionCobAcc;
	}
	
	@Column(name = "estado_propuesta")
	public Integer getEstadoPropuesta() {
		return estadoPropuesta;
	}

	public void setEstadoPropuesta(Integer estadoPropuesta) {
		this.estadoPropuesta = estadoPropuesta;
	}
	
	@Column(name="id_plan", precision=10)
	public String getIdPlan() {
		return idPlan;
	}

	public void setIdPlan(String idPlan) {
		this.idPlan = idPlan;
	}

	@Column(name="nombre_plan", precision=50)
	public String getNombrePlan() {
		return nombrePlan;
	}

	public void setNombrePlan(String nombrePlan) {
		this.nombrePlan = nombrePlan;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_emision", length = 19)
	public Date getFechaEmision() {
		return this.fechaEmisoon;
	}

	public void setFechaEmision(Date fechaEmision) {
		this.fechaEmisoon = fechaEmision;
	}

	// Mixpasarelas - izipay
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_pago_izipay", length = 19)
	public Date getFechaPagoIzipay() {
		return fechaPagoIzipay;
	}
	public void setFechaPagoIzipay(Date fechaPagoIzipay) {
		this.fechaPagoIzipay = fechaPagoIzipay;
	}

	@Column(name = "id_pago_izipay", length = 100)
	public String getIdPagoIzipay() {
		return idPagoIzipay;
	}
	public void setIdPagoIzipay(String idPagoIzipay) {
		this.idPagoIzipay = idPagoIzipay;
	}
}