package pe.interseguro.siv.common.persistence.db.mysql.domain;
// Generated 03/09/2019 02:25:16 PM by Hibernate Tools 4.3.2-SNAPSHOT


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SolicitudBeneficiario generated by hbm2java
 */
@Entity
@Table(name="solicitud_beneficiario"
    ,catalog="siv_db"
)
public class SolicitudBeneficiario  implements java.io.Serializable {


     /**
	 * 
	 */
	 private static final long serialVersionUID = 4414470657631602812L;
	 private Long idSolicitudBeneficiario;
     private Solicitud solicitud;
     private String tipoBeneficiario;
     private String nombres;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private Date fechaNacimiento;
     private String tipoDocumento;
     private String numeroDocumento;
     private String tipoRelacion;
     private Integer distribucion;
     private String usuarioCrea;
     private Date fechaCrea;
     private String usuarioModif;
     private Date fechaModif;

    public SolicitudBeneficiario() {
    }

	
    public SolicitudBeneficiario(Solicitud solicitud, String tipoBeneficiario, String usuarioCrea, Date fechaCrea) {
        this.idSolicitudBeneficiario = idSolicitudBeneficiario;
        this.solicitud = solicitud;
        this.tipoBeneficiario = tipoBeneficiario;
        this.usuarioCrea = usuarioCrea;
        this.fechaCrea = fechaCrea;
    }
    public SolicitudBeneficiario(Solicitud solicitud, String tipoBeneficiario, String nombres, String apellidoPaterno, String apellidoMaterno, Date fechaNacimiento, String tipoDocumento, String numeroDocumento, String tipoRelacion, Integer distribucion, String usuarioCrea, Date fechaCrea, String usuarioModif, Date fechaModif) {
       this.idSolicitudBeneficiario = idSolicitudBeneficiario;
       this.solicitud = solicitud;
       this.tipoBeneficiario = tipoBeneficiario;
       this.nombres = nombres;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.fechaNacimiento = fechaNacimiento;
       this.tipoDocumento = tipoDocumento;
       this.numeroDocumento = numeroDocumento;
       this.tipoRelacion = tipoRelacion;
       this.distribucion = distribucion;
       this.usuarioCrea = usuarioCrea;
       this.fechaCrea = fechaCrea;
       this.usuarioModif = usuarioModif;
       this.fechaModif = fechaModif;
    }
   
    @Id 
    @GeneratedValue(strategy = IDENTITY)
    @Column(name="id_solicitud_beneficiario", unique=true, nullable=false)
    public Long getIdSolicitudBeneficiario() {
        return this.idSolicitudBeneficiario;
    }
    
    public void setIdSolicitudBeneficiario(Long idSolicitudBeneficiario) {
        this.idSolicitudBeneficiario = idSolicitudBeneficiario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_solicitud", nullable=false)
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }

    
    @Column(name="tipo_beneficiario", nullable=false, length=1)
    public String getTipoBeneficiario() {
        return this.tipoBeneficiario;
    }
    
    public void setTipoBeneficiario(String tipoBeneficiario) {
        this.tipoBeneficiario = tipoBeneficiario;
    }

    
    @Column(name="nombres", length=100)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellido_paterno", length=50)
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }

    
    @Column(name="apellido_materno", length=50)
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_nacimiento", length=10)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    
    @Column(name="tipo_documento", length=1)
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }

    
    @Column(name="numero_documento", length=20)
    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }

    
    @Column(name="tipo_relacion", length=2)
    public String getTipoRelacion() {
        return this.tipoRelacion;
    }
    
    public void setTipoRelacion(String tipoRelacion) {
        this.tipoRelacion = tipoRelacion;
    }

    
    @Column(name="distribucion")
    public Integer getDistribucion() {
        return this.distribucion;
    }
    
    public void setDistribucion(Integer distribucion) {
        this.distribucion = distribucion;
    }

    
    @Column(name="usuario_crea", nullable=false, length=50)
    public String getUsuarioCrea() {
        return this.usuarioCrea;
    }
    
    public void setUsuarioCrea(String usuarioCrea) {
        this.usuarioCrea = usuarioCrea;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_crea", nullable=false, length=19)
    public Date getFechaCrea() {
        return this.fechaCrea;
    }
    
    public void setFechaCrea(Date fechaCrea) {
        this.fechaCrea = fechaCrea;
    }

    
    @Column(name="usuario_modif", length=50)
    public String getUsuarioModif() {
        return this.usuarioModif;
    }
    
    public void setUsuarioModif(String usuarioModif) {
        this.usuarioModif = usuarioModif;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modif", length=19)
    public Date getFechaModif() {
        return this.fechaModif;
    }
    
    public void setFechaModif(Date fechaModif) {
        this.fechaModif = fechaModif;
    }




}


