package pe.interseguro.siv.common.persistence.db.mysql.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="solicitud_datos_adicionales"
    ,catalog="siv_db"
)
public class SolicitudDatosAdicionales implements Serializable {
	
	 private static final long serialVersionUID = -9164555947478385026L;
	 
    private Long idSolicitudDatosAdicionales;
    private Solicitud solicitud;
    private String esSujetoObligadoAsegurado;
    private String esSujetoObligadoContratante;
    private String esPepAsegurado;
    private String esPepContratante;
    private String profesionAsegurado;
    private String profesionContratante;
    private String actividadEconomicaAsegurado;
    private String actividadEconomicaContratante;
    private String lugarTrabajoAsegurado;
    private String lugarTrabajoContratante;

    public SolicitudDatosAdicionales() {
    }

    public SolicitudDatosAdicionales(Solicitud solicitud, String esSujetoObligadoAsegurado, String esSujetoObligadoContratante, 
    String esPepAsegurado, String esPepContratante,String profesionAsegurado, String profesionContratante, 
    String actividadEconomicaAsegurado, String actividadEconomicaContratante, String lugarTrabajoAsegurado, String lugarTrabajoContratante) {
        this.idSolicitudDatosAdicionales = idSolicitudDatosAdicionales;
        this.solicitud = solicitud;
        this.esSujetoObligadoAsegurado = esSujetoObligadoAsegurado;
        this.esSujetoObligadoContratante = esSujetoObligadoContratante;
        this.esPepAsegurado = esPepAsegurado;
        this.esPepContratante = esPepContratante;
        this.profesionAsegurado = profesionAsegurado;
        this.profesionContratante = profesionContratante;
        this.actividadEconomicaAsegurado = actividadEconomicaAsegurado;
        this.actividadEconomicaContratante = actividadEconomicaContratante;
        this.lugarTrabajoAsegurado = lugarTrabajoAsegurado;
        this.lugarTrabajoContratante = lugarTrabajoContratante;
    }

    @Id 
    @GeneratedValue(strategy = IDENTITY)
    @Column(name="id_solicitud_datos_adicionales", unique=true, nullable=false)
    public Long getIdSolicitudDatosAdicionales() {
        return this.idSolicitudDatosAdicionales;
    }
    
    public void setIdSolicitudDatosAdicionales(Long idSolicitudDatosAdicionales) {
        this.idSolicitudDatosAdicionales = idSolicitudDatosAdicionales;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_solicitud", nullable=false)
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }

    @Column(name="es_pep_asegurado", length=1)
    public String getEsPepAsegurado() {
        return this.esPepAsegurado;
    }
    
    public void setEsPepAsegurado(String esPepAsegurado) {
        this.esPepAsegurado = esPepAsegurado;
    }

    @Column(name="es_pep_contratante", length=1)
    public String getEsPepContratante() {
        return this.esPepContratante;
    }
    
    public void setEsPepContratante(String esPepContratante) {
        this.esPepContratante = esPepContratante;
    }

    @Column(name="es_sujeto_obligado_asegurado", length=1)
    public String getEsSujetoObligadoAsegurado() {
        return this.esSujetoObligadoAsegurado;
    }
    
    public void setEsSujetoObligadoAsegurado(String esSujetoObligadoAsegurado) {
        this.esSujetoObligadoAsegurado = esSujetoObligadoAsegurado;
    }

    @Column(name="es_sujeto_obligado_contratante", length=1)
    public String getEsSujetoObligadoContratante() {
        return this.esSujetoObligadoContratante;
    }
    
    public void setEsSujetoObligadoContratante(String esSujetoObligadoContratante) {
        this.esSujetoObligadoContratante = esSujetoObligadoContratante;
    }

    @Column(name="lugar_trabajo_asegurado", length=3)
    public String getLugarTrabajoAsegurado() {
        return this.lugarTrabajoAsegurado;
    }

    public void setLugarTrabajoAsegurado(String lugarTrabajoAsegurado) {
        this.lugarTrabajoAsegurado = lugarTrabajoAsegurado;
    }

    @Column(name="lugar_trabajo_contratante", length=3)
    public String getLugarTrabajoContratante() {
        return this.lugarTrabajoContratante;
    }

    public void setLugarTrabajoContratante(String lugarTrabajoContratante) {
        this.lugarTrabajoContratante = lugarTrabajoContratante;
    }

    @Column(name="profesion_asegurado", length=3)
    public String getProfesionAsegurado() {
        return this.profesionAsegurado;
    }

    public void setProfesionAsegurado(String profesionAsegurado) {
        this.profesionAsegurado = profesionAsegurado;
    }

    @Column(name="profesion_contratante", length=3)
    public String getProfesionContratante() {
        return this.profesionContratante;
    }

    public void setProfesionContratante(String profesionContratante) {
        this.profesionContratante = profesionContratante;
    }

    @Column(name="actividad_economica_asegurado", length=3)
    public String getActividadEconomicaAsegurado() {
        return this.actividadEconomicaAsegurado;
    }
    
    public void setActividadEconomicaAsegurado(String actividadEconomicaAsegurado) {
        this.actividadEconomicaAsegurado = actividadEconomicaAsegurado;
    }

    @Column(name="actividad_economica_contratante", length=3)
    public String getActividadEconomicaContratante() {
        return this.actividadEconomicaContratante;
    }
    
    public void setActividadEconomicaContratante(String actividadEconomicaContratante) {
        this.actividadEconomicaContratante = actividadEconomicaContratante;
    }

}
