package pe.interseguro.siv.common.persistence.db.mysql.domain;
// Generated 03/09/2019 02:25:16 PM by Hibernate Tools 4.3.2-SNAPSHOT


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SolicitudDps generated by hbm2java
 */
@Entity
@Table(name="solicitud_dps"
    ,catalog="siv_db"
)
public class SolicitudDps  implements java.io.Serializable {


     /**
	 * 
	 */
	 private static final long serialVersionUID = -9164555947478385026L;
	 private Long idSolicitudDps;
     private Solicitud solicitud;
     private Float estatura;
     private Float peso;
     private Float imc;
     private Integer pesoVariacionCantidad;
     private Integer pesoVariacion;
     private Boolean pesoAumentoDisminuyo;
     private Float pesoAdCantidad;
     private String pesoMotivo;
     private Boolean fumador;
     private String fumadorCantidad;
     private String fumadorFrecuencia;
     private Boolean drogas;
     private String drogasFecha;
     private Boolean alcohol;
     private String alcoholCantidad;
     private String alcoholFrecuencia;
     private String usuarioCrea;
     private Date fechaCrea;
     private String usuarioModif;
     private Date fechaModif;
     private Set<SolicitudDpsPregunta> solicitudDpsPreguntas = new HashSet<SolicitudDpsPregunta>(0);

    public SolicitudDps() {
    }

	
    public SolicitudDps(Solicitud solicitud, String usuarioCrea, Date fechaCrea) {
        this.idSolicitudDps = idSolicitudDps;
        this.solicitud = solicitud;
        this.usuarioCrea = usuarioCrea;
        this.fechaCrea = fechaCrea;
    }
    public SolicitudDps(Solicitud solicitud, Float estatura, Float peso, Float imc, Integer pesoVariacionCantidad, Integer pesoVariacion, Boolean pesoAumentoDisminuyo, Float pesoAdCantidad, String pesoMotivo, Boolean fumador, String fumadorCantidad, String fumadorFrecuencia, Boolean drogas, String drogasFecha, Boolean alcohol, String alcoholCantidad, String alcoholFrecuencia, String usuarioCrea, Date fechaCrea, String usuarioModif, Date fechaModif, Set<SolicitudDpsPregunta> solicitudDpsPreguntas) {
       this.idSolicitudDps = idSolicitudDps;
       this.solicitud = solicitud;
       this.estatura = estatura;
       this.peso = peso;
       this.imc = imc;
       this.pesoVariacionCantidad = pesoVariacionCantidad;
       this.pesoVariacion = pesoVariacion;
       this.pesoAumentoDisminuyo = pesoAumentoDisminuyo;
       this.pesoAdCantidad = pesoAdCantidad;
       this.pesoMotivo = pesoMotivo;
       this.fumador = fumador;
       this.fumadorCantidad = fumadorCantidad;
       this.fumadorFrecuencia = fumadorFrecuencia;
       this.drogas = drogas;
       this.drogasFecha = drogasFecha;
       this.alcohol = alcohol;
       this.alcoholCantidad = alcoholCantidad;
       this.alcoholFrecuencia = alcoholFrecuencia;
       this.usuarioCrea = usuarioCrea;
       this.fechaCrea = fechaCrea;
       this.usuarioModif = usuarioModif;
       this.fechaModif = fechaModif;
       this.solicitudDpsPreguntas = solicitudDpsPreguntas;
    }
   
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name="id_solicitud_dps", unique=true, nullable=false)
    public Long getIdSolicitudDps() {
        return this.idSolicitudDps;
    }
    
    public void setIdSolicitudDps(Long idSolicitudDps) {
        this.idSolicitudDps = idSolicitudDps;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_solicitud", nullable=false)
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }

    
    @Column(name="estatura", precision=5)
    public Float getEstatura() {
        return this.estatura;
    }
    
    public void setEstatura(Float estatura) {
        this.estatura = estatura;
    }

    
    @Column(name="peso", precision=5)
    public Float getPeso() {
        return this.peso;
    }
    
    public void setPeso(Float peso) {
        this.peso = peso;
    }

    
    @Column(name="imc", precision=5)
    public Float getImc() {
        return this.imc;
    }
    
    public void setImc(Float imc) {
        this.imc = imc;
    }

    
    @Column(name="peso_variacion_cantidad")
    public Integer getPesoVariacionCantidad() {
        return this.pesoVariacionCantidad;
    }
    
    public void setPesoVariacionCantidad(Integer pesoVariacionCantidad) {
        this.pesoVariacionCantidad = pesoVariacionCantidad;
    }

    
    @Column(name="peso_variacion")
    public Integer getPesoVariacion() {
        return this.pesoVariacion;
    }
    
    public void setPesoVariacion(Integer pesoVariacion) {
        this.pesoVariacion = pesoVariacion;
    }

    
    @Column(name="peso_aumento_disminuyo")
    public Boolean getPesoAumentoDisminuyo() {
        return this.pesoAumentoDisminuyo;
    }
    
    public void setPesoAumentoDisminuyo(Boolean pesoAumentoDisminuyo) {
        this.pesoAumentoDisminuyo = pesoAumentoDisminuyo;
    }

    
    @Column(name="peso_ad_cantidad", precision=5)
    public Float getPesoAdCantidad() {
        return this.pesoAdCantidad;
    }
    
    public void setPesoAdCantidad(Float pesoAdCantidad) {
        this.pesoAdCantidad = pesoAdCantidad;
    }

    
    @Column(name="peso_motivo", length=80)
    public String getPesoMotivo() {
        return this.pesoMotivo;
    }
    
    public void setPesoMotivo(String pesoMotivo) {
        this.pesoMotivo = pesoMotivo;
    }

    
    @Column(name="fumador")
    public Boolean getFumador() {
        return this.fumador;
    }
    
    public void setFumador(Boolean fumador) {
        this.fumador = fumador;
    }

    
    @Column(name="fumador_cantidad", length=50)
    public String getFumadorCantidad() {
        return this.fumadorCantidad;
    }
    
    public void setFumadorCantidad(String fumadorCantidad) {
        this.fumadorCantidad = fumadorCantidad;
    }

    
    @Column(name="fumador_frecuencia", length=1)
    public String getFumadorFrecuencia() {
        return this.fumadorFrecuencia;
    }
    
    public void setFumadorFrecuencia(String fumadorFrecuencia) {
        this.fumadorFrecuencia = fumadorFrecuencia;
    }

    
    @Column(name="drogas")
    public Boolean getDrogas() {
        return this.drogas;
    }
    
    public void setDrogas(Boolean drogas) {
        this.drogas = drogas;
    }

    @Column(name="drogas_fecha", length=50)
    public String getDrogasFecha() {
        return this.drogasFecha;
    }
    
    public void setDrogasFecha(String drogasFecha) {
        this.drogasFecha = drogasFecha;
    }

    
    @Column(name="alcohol")
    public Boolean getAlcohol() {
        return this.alcohol;
    }
    
    public void setAlcohol(Boolean alcohol) {
        this.alcohol = alcohol;
    }

    
    @Column(name="alcohol_cantidad", length=50)
    public String getAlcoholCantidad() {
        return this.alcoholCantidad;
    }
    
    public void setAlcoholCantidad(String alcoholCantidad) {
        this.alcoholCantidad = alcoholCantidad;
    }

    
    @Column(name="alcohol_frecuencia", length=1)
    public String getAlcoholFrecuencia() {
        return this.alcoholFrecuencia;
    }
    
    public void setAlcoholFrecuencia(String alcoholFrecuencia) {
        this.alcoholFrecuencia = alcoholFrecuencia;
    }

    
    @Column(name="usuario_crea", nullable=false, length=50)
    public String getUsuarioCrea() {
        return this.usuarioCrea;
    }
    
    public void setUsuarioCrea(String usuarioCrea) {
        this.usuarioCrea = usuarioCrea;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_crea", nullable=false, length=19)
    public Date getFechaCrea() {
        return this.fechaCrea;
    }
    
    public void setFechaCrea(Date fechaCrea) {
        this.fechaCrea = fechaCrea;
    }

    
    @Column(name="usuario_modif", length=50)
    public String getUsuarioModif() {
        return this.usuarioModif;
    }
    
    public void setUsuarioModif(String usuarioModif) {
        this.usuarioModif = usuarioModif;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modif", length=19)
    public Date getFechaModif() {
        return this.fechaModif;
    }
    
    public void setFechaModif(Date fechaModif) {
        this.fechaModif = fechaModif;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="solicitudDps")
    public Set<SolicitudDpsPregunta> getSolicitudDpsPreguntas() {
        return this.solicitudDpsPreguntas;
    }
    
    public void setSolicitudDpsPreguntas(Set<SolicitudDpsPregunta> solicitudDpsPreguntas) {
        this.solicitudDpsPreguntas = solicitudDpsPreguntas;
    }




}


