package pe.interseguro.siv.common.persistence.db.mysql.domain;
// Generated 03/09/2019 02:25:16 PM by Hibernate Tools 4.3.2-SNAPSHOT


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SolicitudDpsPregunta generated by hbm2java
 */
@Entity
@Table(name="solicitud_dps_pregunta"
    ,catalog="siv_db"
)
public class SolicitudDpsPregunta  implements java.io.Serializable {


     /**
	 * 
	 */
	 private static final long serialVersionUID = 2301256009037931062L;
	 private Long idSolicitudDpsPregunta;
     private SolicitudDps solicitudDps;
     private Integer bloquePregunta;
     private String item;
     private String pregunta;
     private Boolean respuesta;
     private String detalle;
     private String enfermedad;
     private String fechaDiagnostico;
     private String condicionActual;
     private String nombreMedicoHospital;
     private String usuarioCrea;
     private Date fechaCrea;
     private String usuarioModif;
     private Date fechaModif;

    public SolicitudDpsPregunta() {
    }

	
    public SolicitudDpsPregunta(SolicitudDps solicitudDps, String usuarioCrea, Date fechaCrea) {
        this.idSolicitudDpsPregunta = idSolicitudDpsPregunta;
        this.solicitudDps = solicitudDps;
        this.usuarioCrea = usuarioCrea;
        this.fechaCrea = fechaCrea;
    }
    public SolicitudDpsPregunta(SolicitudDps solicitudDps, Integer bloquePregunta, String item, String pregunta, Boolean respuesta, String detalle, String enfermedad, String fechaDiagnostico, String condicionActual, String nombreMedicoHospital, String usuarioCrea, Date fechaCrea, String usuarioModif, Date fechaModif) {
       this.idSolicitudDpsPregunta = idSolicitudDpsPregunta;
       this.solicitudDps = solicitudDps;
       this.bloquePregunta = bloquePregunta;
       this.item = item;
       this.pregunta = pregunta;
       this.respuesta = respuesta;
       this.detalle = detalle;
       this.enfermedad = enfermedad;
       this.fechaDiagnostico = fechaDiagnostico;
       this.condicionActual = condicionActual;
       this.nombreMedicoHospital = nombreMedicoHospital;
       this.usuarioCrea = usuarioCrea;
       this.fechaCrea = fechaCrea;
       this.usuarioModif = usuarioModif;
       this.fechaModif = fechaModif;
    }
   
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name="id_solicitud_dps_pregunta", unique=true, nullable=false)
    public Long getIdSolicitudDpsPregunta() {
        return this.idSolicitudDpsPregunta;
    }
    
    public void setIdSolicitudDpsPregunta(Long idSolicitudDpsPregunta) {
        this.idSolicitudDpsPregunta = idSolicitudDpsPregunta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_solicitud_dps", nullable=false)
    public SolicitudDps getSolicitudDps() {
        return this.solicitudDps;
    }
    
    public void setSolicitudDps(SolicitudDps solicitudDps) {
        this.solicitudDps = solicitudDps;
    }

    
    @Column(name="bloque_pregunta", length=1)
    public Integer getbloquePregunta() {
        return this.bloquePregunta;
    }
    
    public void setbloquePregunta(Integer bloquePregunta) {
        this.bloquePregunta = bloquePregunta;
    }

    
    @Column(name="item", length=2)
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }

    
    @Column(name="pregunta", length=2)
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }

    
    @Column(name="respuesta")
    public Boolean getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(Boolean respuesta) {
        this.respuesta = respuesta;
    }

    
    @Column(name="detalle", length=65535)
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }

    
    @Column(name="enfermedad", length=150)
    public String getEnfermedad() {
        return this.enfermedad;
    }
    
    public void setEnfermedad(String enfermedad) {
        this.enfermedad = enfermedad;
    }

    @Column(name="fecha_diagnostico", length=50)
    public String getFechaDiagnostico() {
        return this.fechaDiagnostico;
    }
    
    public void setFechaDiagnostico(String fechaDiagnostico) {
        this.fechaDiagnostico = fechaDiagnostico;
    }

    
    @Column(name="condicion_actual", length=100)
    public String getCondicionActual() {
        return this.condicionActual;
    }
    
    public void setCondicionActual(String condicionActual) {
        this.condicionActual = condicionActual;
    }

    
    @Column(name="nombre_medico_hospital", length=100)
    public String getNombreMedicoHospital() {
        return this.nombreMedicoHospital;
    }
    
    public void setNombreMedicoHospital(String nombreMedicoHospital) {
        this.nombreMedicoHospital = nombreMedicoHospital;
    }

    
    @Column(name="usuario_crea", nullable=false, length=50)
    public String getUsuarioCrea() {
        return this.usuarioCrea;
    }
    
    public void setUsuarioCrea(String usuarioCrea) {
        this.usuarioCrea = usuarioCrea;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_crea", nullable=false, length=19)
    public Date getFechaCrea() {
        return this.fechaCrea;
    }
    
    public void setFechaCrea(Date fechaCrea) {
        this.fechaCrea = fechaCrea;
    }

    
    @Column(name="usuario_modif", length=50)
    public String getUsuarioModif() {
        return this.usuarioModif;
    }
    
    public void setUsuarioModif(String usuarioModif) {
        this.usuarioModif = usuarioModif;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modif", length=19)
    public Date getFechaModif() {
        return this.fechaModif;
    }
    
    public void setFechaModif(Date fechaModif) {
        this.fechaModif = fechaModif;
    }




}


