package pe.interseguro.siv.common.persistence.db.mysql.domain;
// Generated 03/09/2019 02:25:16 PM by Hibernate Tools 4.3.2-SNAPSHOT


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SolicitudProductoDetalle generated by hbm2java
 */
@Entity
@Table(name="solicitud_producto_detalle"
    ,catalog="siv_db"
)
public class SolicitudProductoDetalle  implements java.io.Serializable {


     /**
	 * 
	 */
	 private static final long serialVersionUID = 1976811532704571523L;
	 private Long idSolicitudProductoDetalle;
     private SolicitudProducto solicitudProducto;
     private String cobertura;
     private String tipoCobertura;
     private Float capitalAsegurado;
     private Float primaAnual;
     private String usuarioCrea;
     private Date fechaCrea;
     private String usuarioModif;
     private Date fechaModif;

    public SolicitudProductoDetalle() {
    }

	
    public SolicitudProductoDetalle(SolicitudProducto solicitudProducto, String cobertura, String tipoCobertura, Float capitalAsegurado, Float primaAnual, String usuarioCrea, Date fechaCrea) {
        this.idSolicitudProductoDetalle = idSolicitudProductoDetalle;
        this.solicitudProducto = solicitudProducto;
        this.cobertura = cobertura;
        this.tipoCobertura = tipoCobertura;
        this.capitalAsegurado = capitalAsegurado;
        this.primaAnual = primaAnual;
        this.usuarioCrea = usuarioCrea;
        this.fechaCrea = fechaCrea;
    }
    public SolicitudProductoDetalle(SolicitudProducto solicitudProducto, String cobertura, String tipoCobertura, Float capitalAsegurado, Float primaAnual, String usuarioCrea, Date fechaCrea, String usuarioModif, Date fechaModif) {
       this.idSolicitudProductoDetalle = idSolicitudProductoDetalle;
       this.solicitudProducto = solicitudProducto;
       this.cobertura = cobertura;
       this.tipoCobertura = tipoCobertura;
       this.capitalAsegurado = capitalAsegurado;
       this.primaAnual = primaAnual;
       this.usuarioCrea = usuarioCrea;
       this.fechaCrea = fechaCrea;
       this.usuarioModif = usuarioModif;
       this.fechaModif = fechaModif;
    }
   
    @Id 
    @GeneratedValue(strategy = IDENTITY)
    @Column(name="id_solicitud_producto_detalle", unique=true, nullable=false)
    public Long getIdSolicitudProductoDetalle() {
        return this.idSolicitudProductoDetalle;
    }
    
    public void setIdSolicitudProductoDetalle(Long idSolicitudProductoDetalle) {
        this.idSolicitudProductoDetalle = idSolicitudProductoDetalle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_solicitud_producto", nullable=false)
    public SolicitudProducto getSolicitudProducto() {
        return this.solicitudProducto;
    }
    
    public void setSolicitudProducto(SolicitudProducto solicitudProducto) {
        this.solicitudProducto = solicitudProducto;
    }

    
    @Column(name="cobertura", nullable=false, length=2)
    public String getCobertura() {
        return this.cobertura;
    }
    
    public void setCobertura(String cobertura) {
        this.cobertura = cobertura;
    }

    
    @Column(name="tipo_cobertura", nullable=false, length=1)
    public String getTipoCobertura() {
        return this.tipoCobertura;
    }
    
    public void setTipoCobertura(String tipoCobertura) {
        this.tipoCobertura = tipoCobertura;
    }

    
    @Column(name="capital_asegurado", nullable=false, precision=10)
    public Float getCapitalAsegurado() {
        return this.capitalAsegurado;
    }
    
    public void setCapitalAsegurado(Float capitalAsegurado) {
        this.capitalAsegurado = capitalAsegurado;
    }

    
    @Column(name="prima_anual", nullable=false, precision=10)
    public Float getPrimaAnual() {
        return this.primaAnual;
    }
    
    public void setPrimaAnual(Float primaAnual) {
        this.primaAnual = primaAnual;
    }

    
    @Column(name="usuario_crea", nullable=false, length=50)
    public String getUsuarioCrea() {
        return this.usuarioCrea;
    }
    
    public void setUsuarioCrea(String usuarioCrea) {
        this.usuarioCrea = usuarioCrea;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_crea", nullable=false, length=19)
    public Date getFechaCrea() {
        return this.fechaCrea;
    }
    
    public void setFechaCrea(Date fechaCrea) {
        this.fechaCrea = fechaCrea;
    }

    
    @Column(name="usuario_modif", length=50)
    public String getUsuarioModif() {
        return this.usuarioModif;
    }
    
    public void setUsuarioModif(String usuarioModif) {
        this.usuarioModif = usuarioModif;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modif", length=19)
    public Date getFechaModif() {
        return this.fechaModif;
    }
    
    public void setFechaModif(Date fechaModif) {
        this.fechaModif = fechaModif;
    }




}


