package pe.interseguro.siv.common.persistence.db.mysql.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="solicitud_exigencias_medicas"
    ,catalog="siv_db"
)
public class SolicitudExigenciasMedicas implements Serializable {
    private Long idSolicitudExigenciasMedicas;
    private Solicitud solicitud;
    private String examenesMedicos;
    private String moneda;
    private String edad;
    private String capitalTotal;
    private String tipoCambio;
    private String usuarioCrea;
	private Date fechaCrea;
	private String cumulo;
	private String capital;
	private String responseCumulo;

    public SolicitudExigenciasMedicas() {
    }

    public SolicitudExigenciasMedicas(Solicitud solicitud, String examenesMedicos, String moneda, 
    String edad, String capitalTotal,String tipoCambio,String usuarioCrea, Date fechaCrea, String cumulo, String capital, String responseCumulo) {
        this.idSolicitudExigenciasMedicas = idSolicitudExigenciasMedicas;
        this.solicitud = solicitud;
        this.examenesMedicos = examenesMedicos;
        this.moneda = moneda;
        this.edad = edad;
        this.capitalTotal = capitalTotal;
        this.tipoCambio = tipoCambio;
        this.usuarioCrea = usuarioCrea;
		this.fechaCrea = fechaCrea;
		this.cumulo = cumulo;
		this.capital = capital;
		this.responseCumulo = responseCumulo;
    }

    @Id 
    @GeneratedValue(strategy = IDENTITY)
    @Column(name="id_solicitud_exigencias_medicas", unique=true, nullable=false)
    public Long getIdSolicitudExigenciasMedicas() {
        return this.idSolicitudExigenciasMedicas;
    }
    
    public void setIdSolicitudExigenciasMedicas(Long idSolicitudExigenciasMedicas) {
        this.idSolicitudExigenciasMedicas = idSolicitudExigenciasMedicas;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_solicitud", nullable=false)
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }

    @Column(name="examenes_medicos")
    public String getExamenesMedicos() {
        return this.examenesMedicos;
    }
    
    public void setExamenesMedicos(String examenesMedicos) {
        this.examenesMedicos = examenesMedicos;
    }
    
    @Column(name="moneda", length=5)
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }
    
    @Column(name="edad", length=5)
    public String getEdad() {
        return this.edad;
    }
    
    public void setEdad(String edad) {
        this.edad = edad;
    }
    
    @Column(name="capital_total", length=50)
    public String getCapitalTotal() {
        return this.capitalTotal;
    }
    
    public void setCapitalTotal(String capitalTotal) {
        this.capitalTotal = capitalTotal;
    }
    
    @Column(name="tipo_cambio", length=50)
    public String getTipoCambio() {
        return this.tipoCambio;
    }
    
    public void setTipoCambio(String tipoCambio) {
        this.tipoCambio = tipoCambio;
    }
    
    @Column(name = "usuario_crea", nullable = false, length = 50)
	public String getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(String usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_registro", nullable = false, length = 19)
	public Date getFechaCrea() {
		return this.fechaCrea;
	}

	public void setFechaCrea(Date fechaCrea) {
		this.fechaCrea = fechaCrea;
	}
	
	@Column(name="cumulo", length=5)
    public String getCumulo() {
        return this.cumulo;
    }
    
    public void setCumulo(String cumulo) {
        this.cumulo = cumulo;
    }
    
    @Column(name="capital", length=5)
    public String getCapital() {
        return this.capital;
    }
    
    public void setCapital(String capital) {
        this.capital = capital;
    }
    
    @Column(name="response_cumulo", length=5)
    public String getResponseCumulo() {
        return this.responseCumulo;
    }
    
    public void setResponseCumulo(String responseCumulo) {
        this.responseCumulo = responseCumulo;
    }

}
