package pe.interseguro.siv.common.persistence.db.mysql.domain;
// Generated dic 3, 2021 10:43:00 a.m. by Hibernate Tools 4.3.2-SNAPSHOT


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SolicitudTraspaso generated by hbm2java
 */
@Entity
@Table(name="solicitud_traspaso"
    ,catalog="siv_db"
)
public class SolicitudTraspaso  implements java.io.Serializable {


     private Integer idsolicitudTraspaso;
     private String numPropuesta;
     private String numPropuestaOriginal;
     private Float montoActual;
     private Float montoOriginal;
     private String monedaActual;
     private String monedaOriginal;

    public SolicitudTraspaso() {
    }

	
    public SolicitudTraspaso(String numPropuesta, String numPropuestaOriginal) {
        this.numPropuesta = numPropuesta;
        this.numPropuestaOriginal = numPropuestaOriginal;
    }
    public SolicitudTraspaso(String numPropuesta, String numPropuestaOriginal, Float montoActual, Float montoOriginal, String monedaActual, String monedaOriginal) {
       this.numPropuesta = numPropuesta;
       this.numPropuestaOriginal = numPropuestaOriginal;
       this.montoActual = montoActual;
       this.montoOriginal = montoOriginal;
       this.monedaActual = monedaActual;
       this.monedaOriginal = monedaOriginal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idsolicitud_traspaso", unique=true, nullable=false)
    public Integer getIdsolicitudTraspaso() {
        return this.idsolicitudTraspaso;
    }
    
    public void setIdsolicitudTraspaso(Integer idsolicitudTraspaso) {
        this.idsolicitudTraspaso = idsolicitudTraspaso;
    }

    
    @Column(name="num_propuesta", nullable=false, length=20)
    public String getNumPropuesta() {
        return this.numPropuesta;
    }
    
    public void setNumPropuesta(String numPropuesta) {
        this.numPropuesta = numPropuesta;
    }

    
    @Column(name="num_propuesta_original", nullable=false, length=20)
    public String getNumPropuestaOriginal() {
        return this.numPropuestaOriginal;
    }
    
    public void setNumPropuestaOriginal(String numPropuestaOriginal) {
        this.numPropuestaOriginal = numPropuestaOriginal;
    }

    
    @Column(name="monto_actual", precision=10)
    public Float getMontoActual() {
        return this.montoActual;
    }
    
    public void setMontoActual(Float montoActual) {
        this.montoActual = montoActual;
    }

    
    @Column(name="monto_original", precision=10)
    public Float getMontoOriginal() {
        return this.montoOriginal;
    }
    
    public void setMontoOriginal(Float montoOriginal) {
        this.montoOriginal = montoOriginal;
    }

    @Column(name="moneda_actual", length=1)
    public String getMonedaActual() {
        return this.monedaActual;
    }
    
    public void setMonedaActual(String monedaActual) {
        this.monedaActual = monedaActual;
    }

    
    @Column(name="moneda_original", length=1)
    public String getMonedaOriginal() {
        return this.monedaOriginal;
    }
    
    public void setMonedaOriginal(String monedaOriginal) {
        this.monedaOriginal = monedaOriginal;
    }




}


