package pe.interseguro.siv.common.persistence.db.mysql.domain;
// Generated 03/09/2019 02:25:16 PM by Hibernate Tools 4.3.2-SNAPSHOT


import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.ToString;

/**
 * SolicitudProducto generated by hbm2java
 */
@Entity
@Table(name="solicitud_producto"
    ,catalog="siv_db"
)
@ToString
public class SolicitudProducto  implements  Serializable {


     /**
	 * 
	 */
	 private static final long serialVersionUID = -3522026478530185449L;
	 private Long idSolicitudProducto;
     private Solicitud solicitud;
     private String tipoProducto;
     private String fechaCotizacion;
     private Float montoFondoGarantizado;
     private Integer periodoCoberturaAnual;
     private Integer anualidadPago;
     private String frecuencia;
     private String tipoCuota;
     private String tipoRiesgo;
     private Float primaComercialAnual;
     private Float factorPago;
     private Float primaComercial;
     private Float primaIgv;
     private Integer primaDevolucion;
     private String usuarioCrea;
     private Date fechaCrea;
     private String usuarioModif;
     private Date fechaModif;
     private Set<SolicitudProductoDetalle> solicitudProductoDetalles = new HashSet<SolicitudProductoDetalle>(0);

    public SolicitudProducto() {
    }

	
    public SolicitudProducto(Solicitud solicitud, String tipoProducto, Float montoFondoGarantizado, Integer periodoCoberturaAnual, Integer anualidadPago, String frecuencia, String tipoCuota, Float primaComercialAnual, Float factorPago, Float primaComercial, String usuarioCrea, Date fechaCrea) {
        this.idSolicitudProducto = idSolicitudProducto;
        this.solicitud = solicitud;
        this.tipoProducto = tipoProducto;
        this.montoFondoGarantizado = montoFondoGarantizado;
        this.periodoCoberturaAnual = periodoCoberturaAnual;
        this.anualidadPago = anualidadPago;
        this.frecuencia = frecuencia;
        this.tipoCuota = tipoCuota;
        this.primaComercialAnual = primaComercialAnual;
        this.factorPago = factorPago;
        this.primaComercial = primaComercial;
        this.usuarioCrea = usuarioCrea;
        this.fechaCrea = fechaCrea;
    }
    public SolicitudProducto(Solicitud solicitud, String tipoProducto, Float montoFondoGarantizado, Integer periodoCoberturaAnual, Integer anualidadPago, String frecuencia, String tipoCuota, String tipoRiesgo, Float primaComercialAnual, Float factorPago, Float primaComercial, String usuarioCrea, Date fechaCrea, String usuarioModif, Date fechaModif, Set<SolicitudProductoDetalle> solicitudProductoDetalles) {
       this.idSolicitudProducto = idSolicitudProducto;
       this.solicitud = solicitud;
       this.tipoProducto = tipoProducto;
       this.montoFondoGarantizado = montoFondoGarantizado;
       this.periodoCoberturaAnual = periodoCoberturaAnual;
       this.anualidadPago = anualidadPago;
       this.frecuencia = frecuencia;
       this.tipoCuota = tipoCuota;
       this.tipoRiesgo = tipoRiesgo;
       this.primaComercialAnual = primaComercialAnual;
       this.factorPago = factorPago;
       this.primaComercial = primaComercial;
       this.usuarioCrea = usuarioCrea;
       this.fechaCrea = fechaCrea;
       this.usuarioModif = usuarioModif;
       this.fechaModif = fechaModif;
       this.solicitudProductoDetalles = solicitudProductoDetalles;
    }
   
    @Id 
    @GeneratedValue(strategy = IDENTITY)
    @Column(name="id_solicitud_producto", unique=true, nullable=false)
    public Long getIdSolicitudProducto() {
        return this.idSolicitudProducto;
    }
    
    public void setIdSolicitudProducto(Long idSolicitudProducto) {
        this.idSolicitudProducto = idSolicitudProducto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_solicitud", nullable=false)
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }

    
    @Column(name="tipo_producto", nullable=false, length=2)
    public String getTipoProducto() {
        return this.tipoProducto;
    }
    
    public void setTipoProducto(String tipoProducto) {
        this.tipoProducto = tipoProducto;
    }

    
    @Column(name="monto_fondo_garantizado", nullable=false, precision=10)
    public Float getMontoFondoGarantizado() {
        return this.montoFondoGarantizado;
    }
    
    public void setMontoFondoGarantizado(Float montoFondoGarantizado) {
        this.montoFondoGarantizado = montoFondoGarantizado;
    }

    
    @Column(name="periodo_cobertura_anual", nullable=false)
    public Integer getPeriodoCoberturaAnual() {
        return this.periodoCoberturaAnual;
    }
    
    public void setPeriodoCoberturaAnual(Integer periodoCoberturaAnual) {
        this.periodoCoberturaAnual = periodoCoberturaAnual;
    }

    
    @Column(name="anualidad_pago", nullable=false)
    public Integer getAnualidadPago() {
        return this.anualidadPago;
    }
    
    public void setAnualidadPago(Integer anualidadPago) {
        this.anualidadPago = anualidadPago;
    }

    
    @Column(name="frecuencia", nullable=false, length=1)
    public String getFrecuencia() {
        return this.frecuencia;
    }
    
    public void setFrecuencia(String frecuencia) {
        this.frecuencia = frecuencia;
    }

    
    @Column(name="tipo_cuota", nullable=false, length=1)
    public String getTipoCuota() {
        return this.tipoCuota;
    }
    
    public void setTipoCuota(String tipoCuota) {
        this.tipoCuota = tipoCuota;
    }

    
    @Column(name="tipo_riesgo", length=45)
    public String getTipoRiesgo() {
        return this.tipoRiesgo;
    }
    
    public void setTipoRiesgo(String tipoRiesgo) {
        this.tipoRiesgo = tipoRiesgo;
    }

    
    @Column(name="prima_comercial_anual", nullable=false, precision=10)
    public Float getPrimaComercialAnual() {
        return this.primaComercialAnual;
    }
    
    public void setPrimaComercialAnual(Float primaComercialAnual) {
        this.primaComercialAnual = primaComercialAnual;
    }

    
    @Column(name="factor_pago", nullable=false, precision=10)
    public Float getFactorPago() {
        return this.factorPago;
    }
    
    public void setFactorPago(Float factorPago) {
        this.factorPago = factorPago;
    }

    
    @Column(name="prima_comercial", nullable=false, precision=10)
    public Float getPrimaComercial() {
        return this.primaComercial;
    }
    
    public void setPrimaComercial(Float primaComercial) {
        this.primaComercial = primaComercial;
    }

    @Column(name="prima_devolucion", nullable=false, precision=10)
    public Integer getPrimaDevolucion() {
        return this.primaDevolucion;
    }
    
    public void setprimaDevolucion(Integer primaDevolucion) {
        this.primaDevolucion = primaDevolucion;
    }
    
    @Column(name="usuario_crea", nullable=false, length=50)
    public String getUsuarioCrea() {
        return this.usuarioCrea;
    }
    
    public void setUsuarioCrea(String usuarioCrea) {
        this.usuarioCrea = usuarioCrea;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_crea", nullable=false, length=19)
    public Date getFechaCrea() {
        return this.fechaCrea;
    }
    
    public void setFechaCrea(Date fechaCrea) {
        this.fechaCrea = fechaCrea;
    }

    
    @Column(name="usuario_modif", length=50)
    public String getUsuarioModif() {
        return this.usuarioModif;
    }
    
    public void setUsuarioModif(String usuarioModif) {
        this.usuarioModif = usuarioModif;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha_modif", length=19)
    public Date getFechaModif() {
        return this.fechaModif;
    }
    
    public void setFechaModif(Date fechaModif) {
        this.fechaModif = fechaModif;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="solicitudProducto")
    public Set<SolicitudProductoDetalle> getSolicitudProductoDetalles() {
        return this.solicitudProductoDetalles;
    }
    
    public void setSolicitudProductoDetalles(Set<SolicitudProductoDetalle> solicitudProductoDetalles) {
        this.solicitudProductoDetalles = solicitudProductoDetalles;
    }

    @Column(name="prima_igv", nullable=false, precision=10)
	public Float getPrimaIgv() {
		return primaIgv;
	}

	public void setPrimaIgv(Float primaIgv) {
		this.primaIgv = primaIgv;
	}

	@Column(name="fecha_cotizacion", length=20)
	public String getFechaCotizacion() {
		return fechaCotizacion;
	}

	public void setFechaCotizacion(String fechaCotizacion) {
		this.fechaCotizacion = fechaCotizacion;
	}

}


