package pe.interseguro.siv.common.persistence.db.mysql.domain;
// Generated May 20, 2019 8:07:22 PM by Hibernate Tools 4.3.2-SNAPSHOT

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Familiar generated by hbm2java
 */
@Entity
@Table(name = "usuario_perfil", catalog = "siv_db")
public class UsuarioPerfil implements java.io.Serializable {

	private Long idUsuarioPerfil;
	private String usuario;
	private String perfil;
	private String usuarioCrea;
	private Date fechaCrea;
	private String usuarioModif;
	private String fechaModif;

	public UsuarioPerfil() {
	}
	
	@Id @GeneratedValue(strategy=IDENTITY)
	@Column(name="id_persona", unique=true, nullable=false)
	public Long getIdUsuarioPerfil() {
		return idUsuarioPerfil;
	}
		
	public void setIdUsuarioPerfil(Long idUsuarioPerfil) {
		this.idUsuarioPerfil = idUsuarioPerfil;
	}
	
	@Column(name = "usuario", nullable = false, length = 50)
	public String getUsuario() {
		return usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "perfil", nullable = false, length = 50)
	public String getPerfil() {
		return perfil;
	}

	public void setPerfil(String perfil) {
		this.perfil = perfil;
	}

	@Column(name = "usuario_crea", nullable = false, length = 50)
	public String getUsuarioCrea() {
		return this.usuarioCrea;
	}

	public void setUsuarioCrea(String usuarioCrea) {
		this.usuarioCrea = usuarioCrea;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_crea", nullable = false, length = 19)
	public Date getFechaCrea() {
		return this.fechaCrea;
	}

	public void setFechaCrea(Date fechaCrea) {
		this.fechaCrea = fechaCrea;
	}

	@Column(name = "usuario_modif", length = 50)
	public String getUsuarioModif() {
		return this.usuarioModif;
	}

	public void setUsuarioModif(String usuarioModif) {
		this.usuarioModif = usuarioModif;
	}

	@Column(name = "fecha_modif", length = 45)
	public String getFechaModif() {
		return this.fechaModif;
	}

	public void setFechaModif(String fechaModif) {
		this.fechaModif = fechaModif;
	}

}
