package pe.interseguro.siv.common.persistence.db.mysql.domain;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Embeddable;

/**
* ViewSolicitudPlaft generated by hbm2java
*/
@Entity
@Table(name = "view_solicitudes_plaft", catalog = "siv_db")
public class ViewSolicitudPlaft implements java.io.Serializable {

    private Long idSolicitud;
    private String numeroPropuesta;
    private Float primaAnualizada;
    private String producto;
    private String moneda;
    private String contratanteTipoDocumento;
    private String contratanteDocumento;
    private String contratanteActividadEconomica;
    private String contratanteProfesion;
    private String contratanteSujetoObligado;
    private String contratanteNacionalidad;
    private String contratantePep;
    private String contratanteNombres;
    private String contratanteApellidoPaterno;
    private String contratanteApellidoMaterno;
    private String contratanteRazonSocial;
    private String aseguradoTipoDocumento;
    private String aseguradoDocumento;
    private String aseguradoActividadEconomica;
    private String aseguradoProfesion;
    private String aseguradoSujetoObligado;
    private String aseguradoNacionalidad;
    private String aseguradoPep;
    private String aseguradoNombres;
    private String aseguradoApellidoPaterno;
    private String aseguradoApellidoMaterno;
    private String aseguradoRazonSocial;
    private String contratanteResidencia;
    private String aseguradoResidencia;
	
	
	
	@Id @GeneratedValue(strategy=IDENTITY)
	@Column(name="id_solicitud", unique=true, nullable=false)
	public Long getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(Long idSolicitud) {
        this.idSolicitud = idSolicitud;
    }


    @Column(name="numero_propuesta", length=20)
    public String getNumeroPropuesta() {
        return this.numeroPropuesta;
    }
    
    public void setNumeroPropuesta(String numeroPropuesta) {
        this.numeroPropuesta = numeroPropuesta;
    }


    @Column(name="prima_anualizada", precision=10)
    public Float getPrimaAnualizada() {
        return this.primaAnualizada;
    }
    
    public void setPrimaAnualizada(Float primaAnualizada) {
        this.primaAnualizada = primaAnualizada;
    }


    @Column(name="producto", nullable=false, length=16)
    public String getProducto() {
        return this.producto;
    }
    
    public void setProducto(String producto) {
        this.producto = producto;
    }


    @Column(name="moneda", length=16)
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }


    @Column(name="contratante_tipo_documento", length=200)
    public String getContratanteTipoDocumento() {
        return this.contratanteTipoDocumento;
    }
    
    public void setContratanteTipoDocumento(String contratanteTipoDocumento) {
        this.contratanteTipoDocumento = contratanteTipoDocumento;
    }


    @Column(name="contratante_documento", length=20)
    public String getContratanteDocumento() {
        return this.contratanteDocumento;
    }
    
    public void setContratanteDocumento(String contratanteDocumento) {
        this.contratanteDocumento = contratanteDocumento;
    }


    @Column(name="contratante_actividad_economica", length=200)
    public String getContratanteActividadEconomica() {
        return this.contratanteActividadEconomica;
    }
    
    public void setContratanteActividadEconomica(String contratanteActividadEconomica) {
        this.contratanteActividadEconomica = contratanteActividadEconomica;
    }


    @Column(name="contratante_profesion", length=200)
    public String getContratanteProfesion() {
        return this.contratanteProfesion;
    }
    
    public void setContratanteProfesion(String contratanteProfesion) {
        this.contratanteProfesion = contratanteProfesion;
    }


    @Column(name="contratante_sujeto_obligado", nullable=false, length=33)
    public String getContratanteSujetoObligado() {
        return this.contratanteSujetoObligado;
    }
    
    public void setContratanteSujetoObligado(String contratanteSujetoObligado) {
        this.contratanteSujetoObligado = contratanteSujetoObligado;
    }


    @Column(name="contratante_nacionalidad", length=200)
    public String getContratanteNacionalidad() {
        return this.contratanteNacionalidad;
    }
    
    public void setContratanteNacionalidad(String contratanteNacionalidad) {
        this.contratanteNacionalidad = contratanteNacionalidad;
    }


    @Column(name="contratante_pep", nullable=false, length=21)
    public String getContratantePep() {
        return this.contratantePep;
    }
    
    public void setContratantePep(String contratantePep) {
        this.contratantePep = contratantePep;
    }


    @Column(name="contratante_nombres", length=100)
    public String getContratanteNombres() {
        return this.contratanteNombres;
    }
    
    public void setContratanteNombres(String contratanteNombres) {
        this.contratanteNombres = contratanteNombres;
    }


    @Column(name="contratante_apellido_paterno", length=50)
    public String getContratanteApellidoPaterno() {
        return this.contratanteApellidoPaterno;
    }
    
    public void setContratanteApellidoPaterno(String contratanteApellidoPaterno) {
        this.contratanteApellidoPaterno = contratanteApellidoPaterno;
    }


    @Column(name="contratante_apellido_materno", length=50)
    public String getContratanteApellidoMaterno() {
        return this.contratanteApellidoMaterno;
    }
    
    public void setContratanteApellidoMaterno(String contratanteApellidoMaterno) {
        this.contratanteApellidoMaterno = contratanteApellidoMaterno;
    }


    @Column(name="contratante_razon_social", length=100)
    public String getContratanteRazonSocial() {
        return this.contratanteRazonSocial;
    }
    
    public void setContratanteRazonSocial(String contratanteRazonSocial) {
        this.contratanteRazonSocial = contratanteRazonSocial;
    }


    @Column(name="asegurado_tipo_documento", length=200)
    public String getAseguradoTipoDocumento() {
        return this.aseguradoTipoDocumento;
    }
    
    public void setAseguradoTipoDocumento(String aseguradoTipoDocumento) {
        this.aseguradoTipoDocumento = aseguradoTipoDocumento;
    }


    @Column(name="asegurado_documento", length=20)
    public String getAseguradoDocumento() {
        return this.aseguradoDocumento;
    }
    
    public void setAseguradoDocumento(String aseguradoDocumento) {
        this.aseguradoDocumento = aseguradoDocumento;
    }


    @Column(name="asegurado_actividad_economica", length=200)
    public String getAseguradoActividadEconomica() {
        return this.aseguradoActividadEconomica;
    }
    
    public void setAseguradoActividadEconomica(String aseguradoActividadEconomica) {
        this.aseguradoActividadEconomica = aseguradoActividadEconomica;
    }


    @Column(name="asegurado_profesion", length=200)
    public String getAseguradoProfesion() {
        return this.aseguradoProfesion;
    }
    
    public void setAseguradoProfesion(String aseguradoProfesion) {
        this.aseguradoProfesion = aseguradoProfesion;
    }


    @Column(name="asegurado_sujeto_obligado", nullable=false, length=31)
    public String getAseguradoSujetoObligado() {
        return this.aseguradoSujetoObligado;
    }
    
    public void setAseguradoSujetoObligado(String aseguradoSujetoObligado) {
        this.aseguradoSujetoObligado = aseguradoSujetoObligado;
    }


    @Column(name="asegurado_nacionalidad", length=200)
    public String getAseguradoNacionalidad() {
        return this.aseguradoNacionalidad;
    }
    
    public void setAseguradoNacionalidad(String aseguradoNacionalidad) {
        this.aseguradoNacionalidad = aseguradoNacionalidad;
    }


    @Column(name="asegurado_pep", nullable=false, length=19)
    public String getAseguradoPep() {
        return this.aseguradoPep;
    }
    
    public void setAseguradoPep(String aseguradoPep) {
        this.aseguradoPep = aseguradoPep;
    }


    @Column(name="asegurado_nombres", length=100)
    public String getAseguradoNombres() {
        return this.aseguradoNombres;
    }
    
    public void setAseguradoNombres(String aseguradoNombres) {
        this.aseguradoNombres = aseguradoNombres;
    }


    @Column(name="asegurado_apellido_paterno", length=50)
    public String getAseguradoApellidoPaterno() {
        return this.aseguradoApellidoPaterno;
    }
    
    public void setAseguradoApellidoPaterno(String aseguradoApellidoPaterno) {
        this.aseguradoApellidoPaterno = aseguradoApellidoPaterno;
    }


    @Column(name="asegurado_apellido_materno", length=50)
    public String getAseguradoApellidoMaterno() {
        return this.aseguradoApellidoMaterno;
    }
    
    public void setAseguradoApellidoMaterno(String aseguradoApellidoMaterno) {
        this.aseguradoApellidoMaterno = aseguradoApellidoMaterno;
    }


    @Column(name="asegurado_razon_social", length=100)
    public String getAseguradoRazonSocial() {
        return this.aseguradoRazonSocial;
    }
    
    public void setAseguradoRazonSocial(String aseguradoRazonSocial) {
        this.aseguradoRazonSocial = aseguradoRazonSocial;
    }


    @Column(name="contratante_residencia", length=200)
    public String getContratanteResidencia() {
        return this.contratanteResidencia;
    }
    
    public void setContratanteResidencia(String contratanteResidencia) {
        this.contratanteResidencia = contratanteResidencia;
    }


    @Column(name="asegurado_residencia", length=200)
    public String getAseguradoResidencia() {
        return this.aseguradoResidencia;
    }
    
    public void setAseguradoResidencia(String aseguradoResidencia) {
        this.aseguradoResidencia = aseguradoResidencia;
    }
	
}
