package pe.interseguro.siv.common.persistence.db.mysql.domain;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
* Familiar generated by hbm2java
*/
@Entity
@Table(name = "view_solicitudes", catalog = "siv_db")
public class ViewSolicitud implements java.io.Serializable {

	protected Long idSolicitud;
	protected String numeroPropuesta;
	protected String numeroPoliza;
	protected String tipoDocumento;
	protected String numeroDocumento;
	protected String cliente;
	protected String subPlan;
	protected Date fechaSolicitud;
	protected int estado;
	protected String estadoNombre;
	
	@Id @GeneratedValue(strategy=IDENTITY)
	@Column(name="id_solicitud", unique=true, nullable=false)
	public Long getIdSolicitud() {
		return idSolicitud;
	}
	
	public void setIdSolicitud(Long idSolicitud) {
		this.idSolicitud = idSolicitud;
	}
	
	@Column(name = "numero_propuesta", length = 50)
	public String getNumeroPropuesta() {
		return numeroPropuesta;
	}
	
	public void setNumeroPropuesta(String numeroPropuesta) {
		this.numeroPropuesta = numeroPropuesta;
	}
	
	@Column(name = "numero_poliza", length = 50)
	public String getNumeroPoliza() {
		return numeroPoliza;
	}
	
	public void setNumeroPoliza(String numeroPoliza) {
		this.numeroPoliza = numeroPoliza;
	}
	
	@Column(name = "tipo_documento", length = 50)
	public String getTipoDocumento() {
		return tipoDocumento;
	}
	
	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}
	
	@Column(name = "numero_documento", length = 50)
	public String getNumeroDocumento() {
		return numeroDocumento;
	}
	
	public void setNumeroDocumento(String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}
	
	@Column(name = "cliente", length = 200)
	public String getCliente() {
		return cliente;
	}
	
	public void setCliente(String cliente) {
		this.cliente = cliente;
	}
	
	@Column(name = "sub_plan",  length = 200)
	public String getSubPlan() {
		return subPlan;
	}
	
	public void setSubPlan(String subPlan) {
		this.subPlan = subPlan;
	}
	
	@Column(name = "fecha_solicitud")
	public Date getFechaSolicitud() {
		return fechaSolicitud;
	}
	
	public void setFechaSolicitud(Date fechaSolicitud) {
		this.fechaSolicitud = fechaSolicitud;
	}
	
	@Column(name = "estado")
	public int getEstado() {
		return estado;
	}
	
	public void setEstado(int estado) {
		this.estado = estado;
	}
	
	@Column(name = "estado_nombre")
	public String getEstadoNombre() {
		return estadoNombre;
	}
	
	public void setEstadoNombre(String codigoEstado) {
		this.estadoNombre = codigoEstado;
	}
	
	
}
