-- MySQL Script generated by MySQL Workbench
-- Fri Oct  4 11:11:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema siv_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema siv_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `siv_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `siv_db`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siv_db`.`persona` ;

CREATE TABLE IF NOT EXISTS `siv_db`.`persona` (
  `id_persona` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo_documento` CHAR(1) NOT NULL,
  `numero_documento` VARCHAR(20) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `edad_actuarial` INT(11) NULL DEFAULT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellido_paterno` VARCHAR(50) NOT NULL,
  `apellido_materno` VARCHAR(50) NOT NULL,
  `genero` CHAR(1) NOT NULL,
  `celular` INT(11) NULL DEFAULT NULL,
  `correo` VARCHAR(200) NULL DEFAULT NULL,
  `profesion` VARCHAR(3) NULL DEFAULT NULL,
  `actividad_economica` VARCHAR(3) NULL DEFAULT NULL,
  `fumador` CHAR(1) NULL DEFAULT NULL,
  `usuario_crea` VARCHAR(50) NOT NULL,
  `fecha_crea` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_modif` VARCHAR(50) NULL DEFAULT NULL,
  `fecha_modif` TIMESTAMP NULL DEFAULT NULL,
  `razon_social` VARCHAR(100) NULL,
  `estado_civil` CHAR(1) NULL,
  `nacionalidad` VARCHAR(3) NULL,
  `direccion_tipo` CHAR(1) NULL,
  `direccion_tipo_des` VARCHAR(100) NULL,
  `direccion_nro_mz` VARCHAR(20) NULL,
  `direccion_interior` VARCHAR(20) NULL,
  `direccion_urbanizacion` VARCHAR(45) NULL,
  `departamento` VARCHAR(3) NULL,
  `provincia` VARCHAR(3) NULL,
  `distrito` VARCHAR(4) NULL,
  `es_pep` CHAR(1) NULL,
  `es_sujeto_obligado` CHAR(1) NULL,
  `centro_trabajo` VARCHAR(100) NULL,
  `ingreso_moneda` CHAR(1) NULL,
  `ingreso_valor` INT(7) NULL,
  `profesion_detalle` VARCHAR(100) NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB
AUTO_INCREMENT = 978
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;

CREATE UNIQUE INDEX `numero_documento_UNIQUE` ON `siv_db`.`persona` (`numero_documento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`solicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`solicitud` ;

CREATE TABLE IF NOT EXISTS `mydb`.`solicitud` (
  `id_solicitud` INT NOT NULL AUTO_INCREMENT,
  `id_asegurado` INT(11) NOT NULL,
  `id_contratante` INT(11) NULL,
  `numero_cotizacion` VARCHAR(20) NOT NULL,
  `numero_propuesta` VARCHAR(20) NULL,
  `numero_poliza` VARCHAR(20) NULL,
  `asegurado_igual_contratante` CHAR(1) NULL,
  `vinculo_asegurado` CHAR(1) NULL,
  `json_contratante` TEXT NULL,
  `estado` CHAR(1) NOT NULL,
  `subplan` CHAR(1) NULL,
  `moneda` CHAR(1) NULL,
  `id_circuito_firma` VARCHAR(10) NULL,
  `tratamiento_asegurado_check` TINYINT(4) NULL,
  `tratamiento_contratante_check` TINYINT(4) NULL,
  `fecha_firma_asegurado` TIMESTAMP NULL,
  `fecha_firma_contratante` TIMESTAMP NULL,
  `nombre_archivo_solicitud` VARCHAR(50) NULL,
  `id_crm_oportunidad` VARCHAR(40) NULL,
  `id_crm_cotizador` VARCHAR(40) NULL,
  `id_crm_usuario` VARCHAR(40) NULL,
  `agente_nombres` VARCHAR(150) NULL,
  `agente_num_vendedor` VARCHAR(20) NULL,
  `fecha_solicitud` TIMESTAMP NULL,
  `usuario_crea` VARCHAR(50) NOT NULL,
  `fecha_crea` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_modif` VARCHAR(50) NULL,
  `fecha_modif` TIMESTAMP NULL,
  PRIMARY KEY (`id_solicitud`),
  CONSTRAINT `fk_solicitud_persona`
    FOREIGN KEY (`id_asegurado`)
    REFERENCES `siv_db`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_persona1`
    FOREIGN KEY (`id_contratante`)
    REFERENCES `siv_db`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_solicitud_persona_idx` ON `mydb`.`solicitud` (`id_asegurado` ASC) VISIBLE;

CREATE INDEX `fk_solicitud_persona1_idx` ON `mydb`.`solicitud` (`id_contratante` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`solicitud_beneficiario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`solicitud_beneficiario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`solicitud_beneficiario` (
  `id_solicitud_beneficiario` INT NOT NULL AUTO_INCREMENT,
  `id_solicitud` INT NOT NULL,
  `tipo_beneficiario` CHAR(1) NOT NULL,
  `nombres` VARCHAR(100) NULL,
  `apellido_paterno` VARCHAR(50) NULL,
  `apellido_materno` VARCHAR(50) NULL,
  `fecha_nacimiento` DATE NULL,
  `tipo_documento` VARCHAR(2) NULL,
  `numero_documento` VARCHAR(20) NULL,
  `tipo_relacion` VARCHAR(2) NULL,
  `distribucion` INT(3) NULL,
  `usuario_crea` VARCHAR(50) NOT NULL,
  `fecha_crea` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_modif` VARCHAR(50) NULL,
  `fecha_modif` TIMESTAMP NULL,
  PRIMARY KEY (`id_solicitud_beneficiario`),
  CONSTRAINT `fk_solicitud_beneficiario_solicitud1`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `mydb`.`solicitud` (`id_solicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_solicitud_beneficiario_solicitud1_idx` ON `mydb`.`solicitud_beneficiario` (`id_solicitud` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`solicitud_dps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`solicitud_dps` ;

CREATE TABLE IF NOT EXISTS `mydb`.`solicitud_dps` (
  `id_solicitud_dps` INT NOT NULL AUTO_INCREMENT,
  `id_solicitud` INT NOT NULL,
  `estatura` FLOAT(5,2) NULL,
  `peso` FLOAT(5,2) NULL,
  `imc` FLOAT(5,2) NULL,
  `peso_variacion_cantidad` INT(3) NULL,
  `peso_variacion` INT(1) NULL,
  `peso_aumento_disminuyo` TINYINT(1) NULL,
  `peso_ad_cantidad` FLOAT(5,2) NULL,
  `peso_motivo` VARCHAR(80) NULL,
  `fumador` TINYINT(1) NULL,
  `fumador_cantidad` VARCHAR(50) NULL,
  `fumador_frecuencia` VARCHAR(50) NULL,
  `drogas` TINYINT(1) NULL,
  `drogas_fecha` VARCHAR(50) NULL,
  `alcohol` TINYINT(1) NULL,
  `alcohol_cantidad` VARCHAR(50) NULL,
  `alcohol_frecuencia` VARCHAR(50) NULL,
  `usuario_crea` VARCHAR(50) NOT NULL,
  `fecha_crea` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_modif` VARCHAR(50) NULL,
  `fecha_modif` TIMESTAMP NULL,
  PRIMARY KEY (`id_solicitud_dps`),
  CONSTRAINT `fk_solicitud_dps_solicitud1`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `mydb`.`solicitud` (`id_solicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_solicitud_dps_solicitud1_idx` ON `mydb`.`solicitud_dps` (`id_solicitud` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`solicitud_dps_pregunta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`solicitud_dps_pregunta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`solicitud_dps_pregunta` (
  `id_solicitud_dps_pregunta` INT NOT NULL AUTO_INCREMENT,
  `id_solicitud_dps` INT NOT NULL,
  `bloque_pregunta` INT(1) NULL,
  `item` VARCHAR(2) NULL,
  `pregunta` VARCHAR(2) NULL,
  `respuesta` TINYINT(1) NULL,
  `detalle` TEXT NULL,
  `enfermedad` VARCHAR(150) NULL,
  `fecha_diagnostico` VARCHAR(50) NULL,
  `condicion_actual` VARCHAR(100) NULL,
  `nombre_medico_hospital` VARCHAR(100) NULL,
  `usuario_crea` VARCHAR(50) NOT NULL,
  `fecha_crea` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_modif` VARCHAR(50) NULL,
  `fecha_modif` TIMESTAMP NULL,
  PRIMARY KEY (`id_solicitud_dps_pregunta`),
  CONSTRAINT `fk_solicitud_dps_pregunta_solicitud_dps1`
    FOREIGN KEY (`id_solicitud_dps`)
    REFERENCES `mydb`.`solicitud_dps` (`id_solicitud_dps`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_solicitud_dps_pregunta_solicitud_dps1_idx` ON `mydb`.`solicitud_dps_pregunta` (`id_solicitud_dps` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`solicitud_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`solicitud_producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`solicitud_producto` (
  `id_solicitud_producto` INT NOT NULL AUTO_INCREMENT,
  `id_solicitud` INT NOT NULL,
  `tipo_producto` VARCHAR(2) NOT NULL,
  `monto_fondo_garantizado` FLOAT(10,2) NOT NULL,
  `periodo_cobertura_anual` INT(3) NOT NULL,
  `anualidad_pago` INT(3) NOT NULL,
  `frecuencia` CHAR(1) NOT NULL,
  `tipo_cuota` CHAR(1) NOT NULL,
  `tipo_riesgo` CHAR(1) NULL,
  `prima_comercial_anual` FLOAT(10,2) NOT NULL,
  `factor_pago` FLOAT(10,2) NOT NULL,
  `prima_comercial` FLOAT(10,2) NOT NULL,
  `usuario_crea` VARCHAR(50) NOT NULL,
  `fecha_crea` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_modif` VARCHAR(50) NULL,
  `fecha_modif` TIMESTAMP NULL,
  PRIMARY KEY (`id_solicitud_producto`),
  CONSTRAINT `fk_solicitud_producto_solicitud1`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `mydb`.`solicitud` (`id_solicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_solicitud_producto_solicitud1_idx` ON `mydb`.`solicitud_producto` (`id_solicitud` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`solicitud_producto_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`solicitud_producto_detalle` ;

CREATE TABLE IF NOT EXISTS `mydb`.`solicitud_producto_detalle` (
  `id_solicitud_producto_detalle` INT NOT NULL AUTO_INCREMENT,
  `id_solicitud_producto` INT NOT NULL,
  `cobertura` VARCHAR(2) NOT NULL,
  `tipo_cobertura` CHAR(1) NOT NULL,
  `capital_asegurado` FLOAT(10,2) NOT NULL,
  `prima_anual` FLOAT(10,2) NOT NULL,
  `usuario_crea` VARCHAR(50) NOT NULL,
  `fecha_crea` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_modif` VARCHAR(50) NULL,
  `fecha_modif` TIMESTAMP NULL,
  PRIMARY KEY (`id_solicitud_producto_detalle`),
  CONSTRAINT `fk_solicitud_producto_detalle_solicitud_producto1`
    FOREIGN KEY (`id_solicitud_producto`)
    REFERENCES `mydb`.`solicitud_producto` (`id_solicitud_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_solicitud_producto_detalle_solicitud_producto1_idx` ON `mydb`.`solicitud_producto_detalle` (`id_solicitud_producto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`solicitud_agente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`solicitud_agente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`solicitud_agente` (
  `idsolicitud_agente` INT NOT NULL AUTO_INCREMENT,
  `codigo_agente` VARCHAR(10) NOT NULL,
  `numero_documento` VARCHAR(12) NULL,
  `nombre_agente` VARCHAR(100) NULL,
  PRIMARY KEY (`idsolicitud_agente`))
ENGINE = InnoDB;

USE `siv_db` ;

-- -----------------------------------------------------
-- Table `siv_db`.`adn`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siv_db`.`adn` ;

CREATE TABLE IF NOT EXISTS `siv_db`.`adn` (
  `id_adn` INT(11) NOT NULL AUTO_INCREMENT,
  `id_persona` INT(11) NOT NULL,
  `id_agente` VARCHAR(50) NULL DEFAULT NULL,
  `id_circuito_firma` VARCHAR(10) NOT NULL,
  `id_oportunidad_crm` VARCHAR(50) NULL DEFAULT NULL,
  `estado` CHAR(1) NULL DEFAULT NULL COMMENT '1: Registrado\\n2: Cotizado',
  `usuario_crea` VARCHAR(50) NOT NULL,
  `fecha_crea` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_modif` VARCHAR(50) NULL DEFAULT NULL,
  `fecha_modif` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id_adn`),
  CONSTRAINT `fk_adn_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `siv_db`.`persona` (`id_persona`))
ENGINE = InnoDB
AUTO_INCREMENT = 747
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;

CREATE INDEX `fk_adn_persona1_idx` ON `siv_db`.`adn` (`id_persona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `siv_db`.`autoguardado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siv_db`.`autoguardado` ;

CREATE TABLE IF NOT EXISTS `siv_db`.`autoguardado` (
  `id_autoguardado` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo_documento` CHAR(1) NOT NULL,
  `numero_documento` VARCHAR(20) NOT NULL,
  `datos_json` BLOB NOT NULL,
  `usuario_crea` VARCHAR(50) NOT NULL,
  `fecha_crea` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_modif` VARCHAR(50) NULL DEFAULT NULL,
  `fecha_modif` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id_autoguardado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;

CREATE UNIQUE INDEX `tipo_documento_UNIQUE` ON `siv_db`.`autoguardado` (`tipo_documento` ASC) VISIBLE;

CREATE UNIQUE INDEX `numero_documento_UNIQUE` ON `siv_db`.`autoguardado` (`numero_documento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `siv_db`.`familiar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siv_db`.`familiar` ;

CREATE TABLE IF NOT EXISTS `siv_db`.`familiar` (
  `id_familiar` INT(11) NOT NULL AUTO_INCREMENT,
  `id_persona` INT(11) NOT NULL,
  `tipo_relacion` VARCHAR(2) NULL DEFAULT NULL,
  `nombres` VARCHAR(200) NULL DEFAULT NULL,
  `edad` INT(11) NULL DEFAULT NULL,
  `usuario_crea` VARCHAR(50) NOT NULL,
  `fecha_crea` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_modif` VARCHAR(50) NULL DEFAULT NULL,
  `fecha_modif` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_familiar`),
  CONSTRAINT `fk_Familiar_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `siv_db`.`persona` (`id_persona`))
ENGINE = InnoDB
AUTO_INCREMENT = 1047
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;

CREATE INDEX `fk_Familiar_persona1_idx` ON `siv_db`.`familiar` (`id_persona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `siv_db`.`multitabla`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siv_db`.`multitabla` ;

CREATE TABLE IF NOT EXISTS `siv_db`.`multitabla` (
  `id_multitabla` INT(11) NOT NULL AUTO_INCREMENT,
  `codigo_tabla` CHAR(3) NOT NULL,
  `nombre_tabla` VARCHAR(100) NOT NULL,
  `codigo` VARCHAR(100) NULL DEFAULT NULL,
  `orden` INT(11) NULL DEFAULT NULL,
  `valor` TEXT NULL DEFAULT NULL,
  `valor_aux` VARCHAR(200) NULL DEFAULT NULL,
  `valor_crm` VARCHAR(200) NULL DEFAULT NULL,
  `valor_flex` VARCHAR(10) NULL DEFAULT NULL,
  `estado` CHAR(1) NULL DEFAULT NULL,
  `estado_tabla` CHAR(1) NOT NULL,
  `usuario_crea` VARCHAR(50) NOT NULL,
  `fecha_crea` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_modif` VARCHAR(50) NULL DEFAULT NULL,
  `fecha_modif` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id_multitabla`))
ENGINE = InnoDB
AUTO_INCREMENT = 921
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `siv_db`.`plan_futuro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siv_db`.`plan_futuro` ;

CREATE TABLE IF NOT EXISTS `siv_db`.`plan_futuro` (
  `id_plan_futuro` INT(11) NOT NULL AUTO_INCREMENT,
  `id_persona` INT(11) NOT NULL,
  `plan_educacion` TINYINT(4) NULL DEFAULT NULL,
  `plan_proyecto` TINYINT(4) NULL DEFAULT NULL,
  `plan_jubilacion` TINYINT(4) NULL DEFAULT NULL,
  `ingreso_titular` FLOAT(10,2) NULL DEFAULT NULL,
  `porcentaje_inversion` FLOAT(4,2) NULL DEFAULT NULL,
  `total_inversion` FLOAT(10,2) NULL DEFAULT NULL,
  `anios_proteger` INT(11) NULL DEFAULT NULL,
  `respaldo_ahorros` FLOAT(10,2) NULL DEFAULT NULL,
  `respaldo_ahorros_check` TINYINT(4) NULL DEFAULT NULL,
  `respaldo_propiedades` FLOAT(10,2) NULL DEFAULT NULL,
  `respaldo_propiedades_check` TINYINT(4) NULL DEFAULT NULL,
  `respaldo_vehiculos` FLOAT(10,2) NULL DEFAULT NULL,
  `respaldo_vehiculos_check` TINYINT(4) NULL DEFAULT NULL,
  `respaldo_seguro_vida` FLOAT(10,2) NULL DEFAULT NULL,
  `respaldo_seguro_vida_check` TINYINT(4) NULL DEFAULT NULL,
  `respaldo_seguro_vida_ley` FLOAT(10,2) NULL DEFAULT NULL,
  `respaldo_seguro_vida_ley_check` TINYINT(4) NULL DEFAULT NULL,
  `capital_proteccion` FLOAT(10,2) NULL DEFAULT NULL,
  `capital_respaldo` FLOAT(10,2) NULL DEFAULT NULL,
  `capital_afp` FLOAT(10,2) NULL DEFAULT NULL,
  `capital_afp_check` TINYINT(4) NULL DEFAULT NULL,
  `capital_total_proteger` FLOAT(10,2) NULL DEFAULT NULL,
  `capital_adicional` FLOAT(10,2) NULL DEFAULT NULL,
  `capital_total_proteger_nuevo` FLOAT(10,2) NULL DEFAULT NULL,
  `usuario_crea` VARCHAR(50) NOT NULL,
  `fecha_crea` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `usuario_modif` VARCHAR(50) NULL DEFAULT NULL,
  `fecha_modif` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_plan_futuro`),
  CONSTRAINT `fk_plan_futuro_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `siv_db`.`persona` (`id_persona`))
ENGINE = InnoDB
AUTO_INCREMENT = 727
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;

CREATE INDEX `fk_plan_futuro_persona1_idx` ON `siv_db`.`plan_futuro` (`id_persona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `siv_db`.`referido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siv_db`.`referido` ;

CREATE TABLE IF NOT EXISTS `siv_db`.`referido` (
  `id_referido` INT(11) NOT NULL AUTO_INCREMENT,
  `id_persona` INT(11) NOT NULL,
  `nombres` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `telefono` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `usuario_crea` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `fecha_crea` TIMESTAMP NOT NULL,
  `usuario_modif` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `fecha_modif` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id_referido`),
  CONSTRAINT `referido_persona_id_persona_fk`
    FOREIGN KEY (`id_persona`)
    REFERENCES `siv_db`.`persona` (`id_persona`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;

CREATE INDEX `referido_persona_id_persona_fk` ON `siv_db`.`referido` (`id_persona` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
